import test from 'node:test';import assert from 'node:assert/strict';
import {newRun,currentRoom,bossDefeated,enrage} from './engine.js';import {enterRoom,stepRun,ensureMetrics} from './simulation.js';import {encounter} from './encounters.js';import {deployRoom,formations} from './formations.js';import {blocked} from './terrain.js';import {seededRandom} from './random.js';import {encodeSave,parseSave} from './storage.js';import {castUltimate,tickRain} from './abilities.js';import {passiveHit} from './passives.js';
test('upper rosters cover six/seven-floor and nine/eight-floor formations with one support cap',()=>{for(const floor of [6,7]){const seen=new Set();for(let seed=0;seed<150;seed++){const enemies=encounter(floor,seededRandom(Math.imul(seed+1,2654435761)>>>0));seen.add(enemies[0].formation);assert.ok(enemies.filter(e=>['starBearer','gravityMage'].includes(e.type)).length<=1);assert.ok(enemies.length>=7&&enemies.length<=10);}assert.equal(seen.size,formations.filter(f=>f.min<=floor).length);}});
test('deployment respects four entrances, cover, separation and saved positions',()=>{for(const p of [{x:48,y:270},{x:912,y:270},{x:480,y:63},{x:480,y:477}]){for(let seed=0;seed<20;seed++){const s=newRun(seed);s.floor=6;s.room=3;s.player.x=p.x;s.player.y=p.y;enterRoom(s);const r=currentRoom(s);assert.ok(r.deployed);for(const e of r.enemies){assert.ok(Math.hypot(e.x-p.x,e.y-p.y)>=155);assert.ok(!blocked(e.x,e.y,22,r.obstacles));for(const n of r.enemies)if(e!==n)assert.ok(Math.hypot(e.x-n.x,e.y-n.y)>=48);}const coords=r.enemies.map(e=>[e.x,e.y]);const copy=parseSave(encodeSave(s));deployRoom(currentRoom(copy),p);assert.deepEqual(currentRoom(copy).enemies.map(e=>[e.x,e.y]),coords);}}});
test('upper introduction packs stay simple and do not retain elite health',()=>{const s=newRun(4);for(const floor of [6,7]){const r=s.floors[floor][1];assert.ok(r.intro);assert.equal(r.enemies.length,4);assert.equal(new Set(r.enemies.map(e=>e.type)).size,2);assert.ok(r.enemies.every(e=>!e.elite&&e.hp===Math.ceil((32+floor*16)*1.25*(['starKnight','royalGuard'].includes(e.type)?1.15:1))));}});
test('gate announces both guardians, survivor fury, and rewards exactly once across reload',()=>{let s=newRun(8);s.floor=6;s.room=s.floors[6].findIndex(r=>r.gate);s.attack=999;s.invulnerable=999;enterRoom(s);let r=currentRoom(s);assert.equal(r.gateBanner,3);assert.ok(r.enemies.every(e=>e.gateTitle));r.enemies[0].hp=0;stepRun(s,.01);assert.ok(r.enemies[0].gateFury);s=parseSave(encodeSave(s));r=currentRoom(s);r.enemies[0].hp=0;assert.ok(stepRun(s,.01).events.includes('gateReward'));const offers=[...r.relicOffers];assert.ok(!stepRun(s,.01).events.includes('gateReward'));assert.deepEqual(r.relicOffers,offers);});
test('return notice survives reload and enrage creates fresh deployment without altering facilities',()=>{const s=newRun(5);s.floor=7;s.room=s.floors[7].findIndex(r=>r.type==='boss');currentRoom(s).enemies=[];const facilities=s.floors.flat().map(r=>[r.x,r.y,r.type,r.used]);assert.equal(bossDefeated(s),'key');const copy=parseSave(encodeSave(s));assert.ok(copy.returnNoticePending&&copy.key);const entrance=copy.floors[0][0];assert.equal(entrance.deployed,false);copy.floor=0;copy.room=0;copy.player.x=480;copy.player.y=220;enterRoom(copy);assert.ok(entrance.deployed);assert.equal(copy.floors.flat().length,facilities.length);});
test('lower descent mixes upper pursuers without adding extra enemy counts',()=>{let pursuers=0;for(let seed=0;seed<100;seed++){const enemies=encounter(0,seededRandom(seed),[],8);assert.ok(enemies.length>=15&&enemies.length<=16);pursuers+=enemies.some(e=>['astralSniper','starKnight'].includes(e.type))?1:0;}assert.ok(pursuers>10&&pursuers<60);});
test('ultimate telemetry counts actual damage and excludes overkill',()=>{const s=newRun(1),r=currentRoom(s);ensureMetrics(s);r.enemies=[{id:0,type:'archer',x:500,y:300,hp:10,max:10}];s.player.ultimate=1;s.player.evolutions={ultimate:'burst'};castUltimate(s);assert.equal(s.metrics.ultimateDamage,10);tickRain(s,.6);assert.equal(s.metrics.ultimateDamage,10);const e={id:1,type:'archer',x:600,y:300,hp:25,max:25};r.enemies.push(e);passiveHit(s,{passive:'turret',passiveDamage:100,x:480,y:300},e);assert.equal(s.metrics.ultimateDamage,35);assert.doesNotThrow(()=>parseSave(encodeSave(s)));});
