import test from 'node:test';import assert from 'node:assert/strict';
import {bindDefenses,enemyDamageFactor,prismShielded} from './enemy-defense.js';
import {hitEnemy} from './progression.js';import {tickElements} from './elements.js';import {castUltimate} from './abilities.js';
import {newRun,currentRoom} from './engine.js';import {parseSave,encodeSave} from './storage.js';import {relicMarkup} from './hud.js';import {updatePoisonEnemy} from './poison.js';
function scene(){const s=newRun(21);s.floor=3;s.room=s.floors[3].findIndex(r=>r.type==='boss');const r=currentRoom(s),e=r.enemies[0];r.enemies.push({id:1,type:'archer',x:700,y:300,hp:500,max:500,cd:999,summoned:true,summoner:e.id});return {s,r,e};}
test('prism shield covers direct, DoT and ultimate, releases immediately after last summon death and resumes',()=>{let {s,r,e}=scene();bindDefenses(r.enemies);assert.ok(prismShielded(e));assert.equal(enemyDamageFactor(e),1/3);let hp=e.hp;hitEnemy({damage:30},e,r.enemies);assert.ok(Math.abs(hp-e.hp-10)<1e-8);e.poisonRadius=42;e.poisonLevel=1;e.poisonStacks=[{time:2,dps:30}];hp=e.hp;tickElements(r,1);assert.ok(Math.abs(hp-e.hp-10)<1e-8);s.player.ultimate=1;s.player.evolutions={ultimate:'burst'};s.player.split=4;s.player.chain=1;hp=e.hp;castUltimate(s);assert.ok(Math.abs(hp-e.hp-20)<1e-8);s=parseSave(encodeSave(s));r=currentRoom(s);e=r.enemies[0];bindDefenses(r.enemies);r.enemies[1].hp=0;assert.equal(enemyDamageFactor(e),1);hp=e.hp;hitEnemy({damage:30},e,r.enemies);assert.ok(Math.abs(hp-e.hp-30)<1e-8);});
test('multiple summons protect until the last dies, ordinary guardian reduction does not multiply',()=>{const {r,e}=scene();r.enemies.push({...r.enemies[1],id:2});bindDefenses(r.enemies);e.protected=true;assert.equal(enemyDamageFactor(e),1/3);r.enemies[1].hp=0;assert.equal(enemyDamageFactor(e),1/3);r.enemies[2].hp=0;e.protected=false;assert.equal(enemyDamageFactor(e),1);});
test('large slime opens with puddles and shorter cadence while preserving minislime summon',()=>{const e={id:0,type:'boss',variant:'slime',stage:0,x:480,y:210,hp:1350,max:1350,cd:0},r={enemies:[e],obstacles:[]};updatePoisonEnemy(e,{x:400,y:350},r,.01);assert.equal(r.hazards.filter(h=>h.kind==='puddle').length,3);assert.equal(e.cd,2.6*.85);e.poisonTurn=2;e.cd=0;updatePoisonEnemy(e,{x:400,y:350},r,.01);assert.equal(r.enemies.filter(e=>e.type==='minislime').length,2);assert.equal(r.hazards.filter(h=>h.kind==='puddle').length,6);});
test('escape key is shown alongside relics without consuming a relic slot',()=>{const p={relics:['boots']};assert.match(relicMarkup(p,true),/1층 탈출 열쇠/);assert.match(relicMarkup(p,true),/순례자의 장화/);assert.doesNotMatch(relicMarkup(p,false),/탈출 열쇠/);assert.deepEqual(p.relics,['boots']);});
