import test from 'node:test';import assert from 'node:assert/strict';
import {newRun,currentRoom,advanceClock} from './engine.js';import {stepRun,enterRoom,ensureMetrics} from './simulation.js';
import {hitEnemy,tickEffects,levelChoices,consumeLevelChoice,applySkill,rerollSkills} from './progression.js';
import {usePotion,castUltimate,tickRain,castBlink,ultimateUnlocked} from './abilities.js';import {chooseEvolution,pendingEvolution} from './evolutions.js';
import {frostShatter} from './skill-tree.js';import {frostAttackRate} from './frost.js';import {tickPassives,passiveHit} from './passives.js';
import {relics,grantRelic,weightedRelic,offerRelics} from './relics.js';import {parseSave,encodeSave} from './storage.js';import {seededRandom} from './random.js';import {eliteDeath,tickBlasts} from './elites.js';
const foe=(id=0,x=600,y=300)=>({id,type:'archer',x,y,hp:1000,max:1000,cd:999,balanceVersion:1});
function setup(){const s=newRun(121);s.attack=999;s.invulnerable=999;currentRoom(s).obstacles=[];currentRoom(s).enemies=[foe()];return s;}
test('potion heals one, locks three seconds, persists and does not consume at full health',()=>{let s=setup();s.player.potions=5;s.player.hp=2;assert.ok(usePotion(s));assert.equal(s.player.hp,3);assert.equal(usePotion(s),false);s=parseSave(encodeSave(s));advanceClock(s,3,true);assert.equal(usePotion(s),false);advanceClock(s,3,false);grantRelic(s.player,'chalice');assert.ok(usePotion(s));assert.equal(s.player.hp,5);advanceClock(s,3,false);assert.equal(usePotion(s),false);assert.equal(s.player.potions,3);});
test('trial contact, projectile and delayed elite explosion are all one heart',()=>{for(const attack of ['contact','shot','blast']){const s=setup(),r=currentRoom(s);s.invulnerable=0;r.trialState='active';if(attack==='contact')r.enemies=[{...foe(),type:'charger',trialChampion:true,x:480,cd:.2,chargeAngle:0}];if(attack==='shot')s.projectiles=[{x:480,y:300,vx:0,vy:0,life:1,enemy:true,damage:24,hit:[]}];if(attack==='blast'){eliteDeath({...foe(),elite:'explosive',trialChampion:true,x:480},r);r.trialState='reward';r.blasts[0].time=.001;}stepRun(s,.01);assert.equal(s.player.hp,4,attack);}});
test('frost levels freeze on 4,3,2,2 hits and scale direct elemental damage',()=>{for(const [level,hits] of [[1,4],[2,3],[3,2],[4,2]]){const e=foe(),p={damage:10,frost:level};for(let i=1;i<=hits;i++){hitEnemy(p,e,[e]);assert.equal(!!e.frozen,i===hits);}assert.ok(Math.abs(e.hp-(1000-hits*10*.92*(1+.05+.05*level)))<1e-8);assert.equal(e.frostStacks,3);assert.equal(frostAttackRate(e),.7);tickEffects(e,1.3);const before=e.frostStacks;hitEnemy(p,e,[e]);assert.equal(e.frostStacks,before);}});
test('frost shard sizes reflect stack count, level four frozen deaths emit twelve',()=>{for(const n of [1,2,3]){const b=[];frostShatter({frost:1},{id:4,x:100,y:100,hp:0,frostStacks:n,frostStackTime:2},b);assert.equal(b.length,6);assert.equal(b[0].shardSize,n*.5);assert.ok(Math.abs(Math.hypot(b[0].vx,b[0].vy)-480)<1e-8);}const b=[];frostShatter({frost:4},{id:4,x:100,y:100,hp:0,frozen:1},b);assert.equal(b.length,12);assert.ok(b.every(b=>b.shardSize===1.5));});
test('element relic boosts frost direct bonus and shards, not duration',()=>{const a=foe(),b=foe();hitEnemy({damage:100,frost:4},a,[a]);hitEnemy({damage:100,frost:4,relics:['crystal']},b,[b]);const id=relics.find(r=>r.stats?.element).id;const c=foe();hitEnemy({damage:100,frost:4,relics:[id]},c,[c]);assert.ok(c.hp<a.hp);const d=foe(),e=foe();hitEnemy({damage:100,frost:4,frostShardAttack:true},d,[d],[],.5);hitEnemy({damage:100,frost:4,frostShardAttack:true,relics:[id]},e,[e],[],.5);assert.ok(e.hp<d.hp);assert.equal(e.slow,d.slow);});
test('ultimate is a single saved offer at 5 and 10, random later, preserved on reroll',()=>{let s=setup();s.player.mainSkill='fire';s.player.fire=1;s.player.level=5;s.pendingLevels=1;s.levelQueue=[5];assert.ok(levelChoices(s,()=>.99).some(k=>k.id==='ultimate'));s=parseSave(encodeSave(s));assert.ok(rerollSkills(s));assert.ok(s.choices.includes('ultimate'));consumeLevelChoice(s);s.player.level=6;s.pendingLevels=1;s.levelQueue=[6];assert.ok(!levelChoices(s,()=>.99).some(k=>k.id==='ultimate'));consumeLevelChoice(s);s.player.level=10;s.pendingLevels=1;s.levelQueue=[10];assert.ok(levelChoices(s,()=>.99).some(k=>k.id==='ultimate'));assert.ok(applySkill(s.player,'ultimate'));consumeLevelChoice(s);assert.equal(pendingEvolution(s.player),'ultimate');assert.ok(chooseEvolution(s.player,'ultimate','turret'));assert.ok(ultimateUnlocked(s.player));s.player.level=11;s.pendingLevels=1;s.levelQueue=[11];assert.ok(!levelChoices(s,()=>0).some(k=>k.id==='ultimate'));});
test('multiple level gains preserve the level five guarantee in the queue',()=>{const s=setup();s.player.mainSkill='fire';s.player.fire=1;s.player.level=6;s.pendingLevels=2;s.levelQueue=[5,6];assert.ok(levelChoices(s,()=>.99).some(k=>k.id==='ultimate'));consumeLevelChoice(s);assert.ok(!levelChoices(s,()=>.99).some(k=>k.id==='ultimate'));});
test('rain hits three times at fixed cast location and preserves partial pulses on reload',()=>{let s=setup();s.player.ultimate=1;s.player.evolutions={ultimate:'burst'};currentRoom(s).enemies.push(foe(1,929));assert.ok(castUltimate(s));assert.equal(currentRoom(s).enemies[0].hp,940);assert.equal(currentRoom(s).enemies[1].hp,1000);s.player.x=100;tickRain(s,.6);assert.equal(currentRoom(s).enemies[0].hp,880);s=parseSave(encodeSave(s));tickRain(s,.6);assert.equal(currentRoom(s).enemies[0].hp,820);tickRain(s,.6);assert.equal(currentRoom(s).arrowRain,null);});
test('turrets shoot, overlap at most twice and retain remaining lifetime across save',()=>{let s=setup();s.player.ultimate=1;s.player.evolutions={ultimate:'turret'};castUltimate(s);tickPassives(s,.01);assert.equal(s.projectiles[0].passive,'turret');s.skill=0;castUltimate(s);s.skill=0;castUltimate(s);assert.equal(currentRoom(s).turrets.length,2);s=parseSave(encodeSave(s));tickPassives(s,19);assert.equal(currentRoom(s).turrets.length,0);});
test('three unique fairies each fire one guided shot per 1.5 seconds',()=>{const s=setup();for(const id of ['sunFairy','snowFairy','stormFairy'])grantRelic(s.player,id);tickPassives(s,1.49);assert.equal(s.projectiles.length,0);tickPassives(s,.01);assert.equal(s.projectiles.length,3);assert.deepEqual(new Set(s.projectiles.map(b=>b.passive)),new Set(['sunFairy','snowFairy','stormFairy']));assert.ok(s.projectiles.every(b=>b.homing));tickPassives(s,1.5);assert.equal(s.projectiles.length,6);assert.doesNotThrow(()=>parseSave(encodeSave(s)));});
test('fairy secondary effects are independent and cannot trigger frost death chains',()=>{const s=setup(),r=currentRoom(s),e=r.enemies[0];r.enemies.push(foe(1,650));passiveHit(s,{passive:'sunFairy',passiveDamage:40},e);assert.deepEqual(e.fairyBurn,{time:3,dps:20});passiveHit(s,{passive:'snowFairy',passiveDamage:50},e);assert.equal(e.slowFactor,.75);const before=r.enemies[1].hp;passiveHit(s,{passive:'stormFairy',passiveDamage:80},e);assert.equal(r.enemies[1].hp,before-40);e.hp=1;e.frozen=1;passiveHit(s,{passive:'sunFairy',passiveDamage:40},e);assert.equal(frostShatter({frost:4},e,[]),false);});
test('unique weights are lower, blink cloak extends immunity and orbit/bell work',()=>{assert.equal(relics.filter(r=>r.grade==='unique').length,6);const random=seededRandom(6);let count=0;for(let i=0;i<10000;i++)if(weightedRelic(relics,random).grade==='unique')count++;assert.ok(count>700&&count<1100);const s=setup();s.invulnerable=0;grantRelic(s.player,'afterimage');grantRelic(s.player,'comet');castBlink(s,{x:1,y:0});assert.equal(s.invulnerable,2.45);assert.ok(Math.abs(s.player.x-742.5)<1e-8);s.player.x=480;grantRelic(s.player,'orbitBlades');grantRelic(s.player,'voidBell');const e=currentRoom(s).enemies[0];e.x=545;tickPassives(s,.01);assert.ok(e.hp<1000);tickPassives(s,12);assert.equal(s.passiveClocks.voidBell,12);});
test('legacy ultimate branch migrates to chosen tower and malformed new states are rejected',()=>{const s=setup();delete s.upgrade21;delete s.player.ultimate;s.player.evolutions={ultimate:'field'};const copy=parseSave(encodeSave(s));assert.equal(copy.player.ultimate,1);assert.equal(copy.player.evolutions.ultimate,'turret');assert.doesNotThrow(()=>parseSave(encodeSave(copy)));currentRoom(copy).turrets=[{x:400,y:300,time:999,clock:0,aim:0}];assert.throws(()=>encodeSave(copy));});

test('bonus skill rewards do not roll the level-up-only ultimate offer',()=>{const s=setup();s.player.level=10;s.player.mainSkill='fire';s.player.fire=1;s.pendingLevels=1;assert.ok(!levelChoices(s,()=>0).some(k=>k.id==='ultimate'));assert.deepEqual(s.ultimateMilestones||[],[]);});
