import {updatePrism,drawPrism} from './prism.js';
import {updatePattern,drawPattern} from './patterns.js';
import {updateRanged,advanceRicochet,drawRanged} from './ranged.js';
import {DODGE_COOLDOWN,ultimateUnlocked,castUltimate} from './abilities.js';
import {updateBrute,drawEnemyDetails} from './brute.js';
import {moveBody,segmentBlocked,steering,drawObstacles,drawMinimap} from './terrain.js';
import {migrateRun,xpRequired,skills,recipes,combinations,skillChoices,applySkill,hitEnemy,tickEffects} from './progression.js';
import {newRun,currentRoom,neighbor,bossDefeated,travel,useShrine,advanceClock,canEscape,timeString} from './engine.js';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d'),SAVE='spirebound.run.v1';
let s=null,paused=true,mode='title',bullets=[],fx=[],keys=new Set(),axis={x:0,y:0},last=performance.now(),saveTick=0,toastTime=0;
const room=()=>currentRoom(s),distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function toast(t){$('notice').textContent=t;toastTime=4;}
function save(){if(s?.status==='playing')try{localStorage.setItem(SAVE,JSON.stringify(s));}catch{toast('저장 공간을 사용할 수 없습니다.');}}
function panel(html){$('overlay').innerHTML=`<div class="panel">${html}</div>`;}
function button(id,fn){$(id)?.addEventListener('click',fn);}
function title(){$('skill').hidden=true;mode='title';paused=true;let exists=false;try{exists=!!localStorage.getItem(SAVE);}catch{}panel(`<small>A JOURNEY UP. A FIGHT BACK.</small><h2>SPIREBOUND</h2><p>미지의 탑에 발을 들인 순간, 출구가 닫혔다.<br>탑의 파수꾼에게서 열쇠를 빼앗고 살아 돌아오세요.</p><p>🏹 왕실 정찰병 · 자동 사격 / 성장 후 궁극기 해금<br>4층 왕복 시험판 · 기록은 이 기기에 저장됩니다.</p><button class="primary" id="start">${exists?'새 도전 (기존 저장 교체)':'탑에 입장하기'} →</button>${exists?'<button id="continue">이어하기</button>':''}`);button('start',()=>{s=newRun();bullets=[];fx=[];resume();save();toast('출구가 봉쇄되었습니다. 계단을 탐색하세요.');});button('continue',()=>{try{s=JSON.parse(localStorage.getItem(SAVE));if(s.version!==1||s.status!=='playing'||!s.floors?.[1]||!s.player)throw Error();migrateRun(s);bullets=[];fx=[];resume();}catch{toast('저장 파일을 읽을 수 없습니다. 새 도전을 시작하세요.');title();}});}
function resume(){s.pendingHeal&&(s.player.hp=Math.min(s.player.max,s.player.hp+35));s.pendingHeal=false;mode='play';paused=false;$('overlay').innerHTML='';keys.clear();axis={x:0,y:0};if(s.pendingLevels)levelUp();}
function pause(){if(!s||s.status!=='playing'||mode==='title'||mode==='level')return;paused=true;mode='pause';keys.clear();axis={x:0,y:0};save();panel('<small>TAKE A BREATH</small><h2>잠시 쉬어가기</h2><p>게임과 기록 시간이 멈췄습니다. 진행 상황이 저장되었습니다.</p><button class="primary" id="resume">계속 탐험</button><button id="quit">저장 후 나가기</button>');button('resume',resume);button('quit',()=>{save();title();});}
function bag(){if(!s||s.status!=='playing'||mode==='title'||mode==='level')return;paused=true;mode='bag';keys.clear();panel(`<small>ROYAL SCOUT / INVENTORY</small><h2>여행자의 가방</h2><p>무기 · ${s.player.weapon?'강화 장궁':'정찰병의 활'} / 공격력 ${s.player.damage}<br>방어구 · ${s.player.armor?'수호자의 가죽옷':'가죽 조끼'}<br>장신구 Ⅰ · ${s.player.unique?'바람의 인장 (화살 적중 시 체력 1 회복)':'비어 있음'}<br>장신구 Ⅱ · 비어 있음</p><p>익힌 기술 · ${skills.filter(k=>s.player[k.id]>0).map(k=>k.name+' '+s.player[k.id]).join(' / ')||'없음'}<br>활성 조합 · ${combinations(s.player).map(c=>c.name).join(' / ')||'없음'}</p><p>물약 ${s.player.potions}개 · 음식 ${s.player.food}개<br>음식은 안전한 방에서 사용하며, 재개할 때 회복됩니다.</p><button id="eat" ${room().enemies.length||!s.player.food||s.pendingHeal?'disabled':''}>음식 먹기 +35 HP</button><button class="primary" id="closeBag">탐험 재개</button>`);button('eat',()=>{s.player.food--;s.pendingHeal=true;save();bag();});button('closeBag',()=>{resume();save();});}
function levelUp(){
 paused=true;mode='level';keys.clear();axis={x:0,y:0};
 let choices=s.choices?.map(id=>skills.find(k=>k.id===id)).filter(k=>k&&(s.player[k.id]||0)<k.max);
 if(!choices?.length)choices=skillChoices(s.player);
 s.choices=choices.map(k=>k.id);save();
 if(!choices.length){s.player.hp=Math.min(s.player.max,s.player.hp+25);s.pendingLevels--;s.choices=null;resume();return;}
 panel('<small>CHOOSE YOUR PATH</small><h2>새로운 깨달음</h2><p>6종의 기술 중 하나를 선택하세요. 함께 익힌 기술은 자동으로 조합됩니다.</p><div class="cards">'+choices.map((k,i)=>'<button id="u'+i+'"><b>'+k.name+' '+((s.player[k.id]||0)+1)+' / '+k.max+'</b><span>'+k.description+'</span><em>'+recipes.filter(r=>r.needs.includes(k.id)).map(r=>r.name+' · '+r.needs.map(id=>skills.find(a=>a.id===id).name).join(' + ')).join('<br>')+'</em></button>').join('')+'</div>');
 choices.forEach((k,i)=>button('u'+i,()=>{const wasUnlocked=ultimateUnlocked(s.player),previous=combinations(s.player).map(c=>c.name);applySkill(s.player,k.id);const unlocked=combinations(s.player).filter(c=>!previous.includes(c.name));if(unlocked.length)toast('조합 완성 · '+unlocked.map(c=>c.name).join(' / '));if(!wasUnlocked&&ultimateUnlocked(s.player)){s.skill=0;toast('궁극기 · 화살비 해금! F 또는 오른쪽 버튼');}s.pendingLevels--;s.choices=null;resume();save();}));
}
function finish(won){s.status=won?'won':'dead';paused=true;mode='result';try{localStorage.removeItem(SAVE);let history=JSON.parse(localStorage.getItem('spirebound.history')||'[]');history.push({won,time:s.elapsed,level:s.player.level,floor:s.floor+1,key:s.key,date:new Date().toISOString()});localStorage.setItem('spirebound.history',JSON.stringify(history.slice(-30)));}catch{}panel(`<small>${won?'THE WAY HOME':'THE SPIRE REMEMBERS'}</small><h2>${won?'탑에서 탈출했습니다':'도전이 끝났습니다'}</h2><p>${won?'열쇠가 잠긴 문을 열었습니다. 당신은 살아 돌아왔습니다.':'탑은 또 한 명의 모험가를 기억합니다.'}</p><p>${timeString(s.elapsed)} · LV ${s.player.level} · 처치 ${s.kills}<br>${s.floor+1}층 · 열쇠 ${s.key?'획득':'미획득'} · ${won?'탈출 성공':'실패'}<br>개인 이력이 기기에 저장되었습니다. 온라인 순위는 추후 지원합니다.</p><button class="primary" id="again">입구로 돌아가기</button>`);button('again',title);}
function potion(){if(paused||!s.player.potions||s.player.hp===s.player.max)return;s.player.potions--;s.player.hp=Math.min(s.player.max,s.player.hp+45);toast('회복 물약 · HP +45');}
function dodge(){if(paused||s.dodge>0)return;s.dodge=DODGE_COOLDOWN;s.invulnerable=.45;let v=movement();if(!v.x&&!v.y)v={x:0,y:-1};moveBody(s.player,v.x*105,v.y*105,room().obstacles);s.player.x=Math.max(50,Math.min(910,s.player.x));s.player.y=Math.max(65,Math.min(475,s.player.y));fx.push({x:s.player.x,y:s.player.y,r:40,t:.35,color:'#d5eed4'});}
function skill(){if(paused||!castUltimate(s))return;room().enemies.forEach(e=>fx.push({x:e.x,y:e.y,r:60,t:.6,color:'#e6c57b'}));toast('궁극기 · 화살비');}
function interaction(){if(!s)return null;const r=room();if(distance(s.player,{x:480,y:115})>78)return null;if(r.type==='fountain'&&!r.used)return ['샘물로 회복',()=>{r.used=true;s.player.hp=Math.min(s.player.max,s.player.hp+60);toast('샘물이 말랐습니다. HP +60');}];if(r.type==='treasure'&&!r.used&&!r.enemies.length)return ['보물 상자 열기',()=>{r.used=true;s.player.weapon++;s.player.damage+=6;s.player.armor+=2;s.player.potions++;s.player.unique=true;toast('강화 장궁 · 수호 가죽옷 · 바람의 인장 획득');}];if((r.type==='up'||r.type==='boss'&&r.used)&&s.floor<s.floors.length-1)return [(s.floor+2)+'층으로 올라가기',()=>changeFloor(s.floor+1)];if(r.type==='down')return [s.floor+'층으로 내려가기',()=>changeFloor(s.floor-1)];if(r.type==='shrine'&&!r.used)return ['고대신의 신전 · 장비 강화',shrine];if(canEscape(s))return ['열쇠로 탈출하기',()=>finish(true)];if(r.type==='exit')return ['출구 봉쇄 · 열쇠 필요',()=>toast('최상층의 수호자가 열쇠를 지키고 있습니다.')];return null;}
function shrine(){paused=true;mode='shrine';keys.clear();panel('<small>ANCIENT SANCTUARY</small><h2>고대신의 축복</h2><p>한 번만 장비를 강화할 수 있습니다. 선택 중 시간은 멈춥니다.</p><button id="blessWeapon">무기 · 공격력 +12</button><button id="blessArmor">방어구 · 방어 +3 / 최대 HP +30</button><button id="leaveShrine">나중에</button>');button('blessWeapon',()=>{useShrine(s,'weapon');resume();save();});button('blessArmor',()=>{useShrine(s,'armor');resume();save();});button('leaveShrine',resume);}
function interact(){if(paused)return;interaction()?.[1]();save();}
function changeFloor(f){if(travel(s,f-s.floor)){bullets=[];fx=[];save();}}
function movement(){let x=axis.x+(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),y=axis.y+(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0),n=Math.max(1,Math.hypot(x,y));return{x:x/n,y:y/n};}
function shoot(x,y,target,speed,enemy=false,angle=0){const a=Math.atan2(target.y-y,target.x-x)+angle;bullets.push({x,y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,enemy,life:3,pierce:enemy?0:s.player.pierce,hit:[]});}
function update(dt){if(!s||paused)return;advanceClock(s,dt,false);let p=s.player,r=room(),v=movement();moveBody(p,v.x*p.speed*dt,v.y*p.speed*dt,r.obstacles);
 const d=p.y<48?0:p.x>930?1:p.y>492?2:p.x<30?3:-1;
 if(d>=0){const n=neighbor(s,d),aligned=d%2===0?Math.abs(p.x-480)<55:Math.abs(p.y-270)<55;if(n>=0&&aligned&&!(r.type==='boss'&&r.enemies.length)){s.room=n;r=room();r.seen=true;p.x=d===1?45:d===3?915:p.x;p.y=d===0?480:d===2?60:p.y;bullets=[];save();}else{p.x=Math.max(31,Math.min(929,p.x));p.y=Math.max(49,Math.min(491,p.y));}}
 let target=r.enemies.filter(e=>e.hp>0&&!segmentBlocked(p,e,r.obstacles,3)).sort((a,b)=>distance(a,p)-distance(b,p))[0];if(target&&s.attack<=0){s.attack=.65/(1+s.player.haste*.2);const count=1+Math.min(4,p.split);for(let i=0;i<count;i++)shoot(p.x,p.y,target,420,false,(i-(count-1)/2)*.14);}
 for(const e of r.enemies){
 tickEffects(e,dt);if(e.hp<=0)continue;if(e.variant==='prism'){const damage=updatePrism(e,p,r.obstacles,dt,bullets);if(damage)hurt(damage);continue;}if(['boss','archer','scatter'].includes(e.type)){const damage=updatePattern(e,p,r.obstacles,dt,bullets,s.key);if(damage)hurt(damage);continue;}if(e.type==='laser'||e.type==='ricochet'){const damage=updateRanged(e,p,r.obstacles,dt,bullets,s.key);if(damage)hurt(damage);continue;}if(e.type==='brute'){const damage=updateBrute(e,p,r.obstacles,dt,s.key);if(damage)hurt(damage);continue;}e.cd-=dt;
 let a=steering(e,p,r.obstacles,e.type==='boss'?32:18),speed=0;
 const ranged=e.type==='archer'||e.type==='scatter';
 if(e.type==='charger'){
  if(e.cd<.95&&e.chargeAngle===undefined)e.chargeAngle=Math.atan2(p.y-e.y,p.x-e.x);
  if(e.cd<.45){a=e.chargeAngle??a;speed=235;}else speed=e.cd<.95?0:35;
 }else speed=e.type==='boss'?28:ranged?(distance(e,p)>250||segmentBlocked(e,p,r.obstacles,3)?25:0):52;
 speed*=(s.key?1.6:1)*(e.slow>0?e.slowFactor:1);moveBody(e,Math.cos(a)*speed*dt,Math.sin(a)*speed*dt,r.obstacles,e.type==='boss'?32:18);e.x=Math.max(40,Math.min(920,e.x));e.y=Math.max(60,Math.min(480,e.y));
 if(e.cd<=0){
  e.cd=(e.type==='boss'?2.1:e.type==='scatter'?3.2:2.7)/(s.key?1.2:1);delete e.chargeAngle;
 }
 if(distance(e,p)<(e.type==='boss'?32:21))hurt(e.type==='boss'?18:9);
 }
 for(const b of bullets){if(b.ricochet){if(advanceRicochet(b,dt,r.obstacles,p))hurt(12);continue;}const next={x:b.x+b.vx*dt,y:b.y+b.vy*dt};if(segmentBlocked(b,next,r.obstacles,3)){b.life=0;continue;}b.x=next.x;b.y=next.y;b.life-=dt;if(b.enemy){if(distance(b,p)<15){hurt(10);b.life=0;}}else for(const e of r.enemies)if(e.hp>0&&!b.hit.includes(e.id)&&distance(b,e)<(e.type==='boss'?32:19)){fx.push(...hitEnemy(p,e,r.enemies));b.hit.push(e.id);if(p.unique)p.hp=Math.min(p.max,p.hp+1);if(b.pierce--<=0){b.life=0;break;}}}
 bullets=bullets.filter(b=>b.life>0&&b.x>25&&b.x<935&&b.y>40&&b.y<500);
 for(const e of r.enemies.filter(e=>e.hp<=0)){s.kills++;if(!s.key){p.xp+=e.type==='boss'?45:12;while(p.xp>=xpRequired(p.level)){p.xp-=xpRequired(p.level);p.level++;s.pendingLevels++;}}if(e.type==='boss'){const result=bossDefeated(s);toast(result==='key'?'열쇠 획득! 1층 출구로 귀환하세요.':'중간 보스 격파! 위층 계단이 열렸습니다.');}else if(Math.random()<.1)p.potions++;}
 r.enemies=r.enemies.filter(e=>e.hp>0);fx.forEach(f=>f.t-=dt);fx=fx.filter(f=>f.t>0);if(p.hp<=0){finish(false);return;}if(s.pendingLevels)levelUp();saveTick+=dt;if(saveTick>2){saveTick=0;save();}if(toastTime>0){toastTime-=dt;if(toastTime<=0)$('notice').textContent='';}
}
function hurt(n){if(s.invulnerable>0)return;s.player.hp=Math.max(0,s.player.hp-Math.max(1,n-s.player.armor));s.invulnerable=.65;}
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),w,h);}
function text(t,x,y,c='#c8d3bd',size=12){ctx.fillStyle=c;ctx.font=`${size}px monospace`;ctx.textAlign='center';ctx.fillText(t,x,y);}
function sprite(x,y,type){ctx.save();ctx.translate(Math.round(x),Math.round(y));rect(-13,13,27,7,'#0006');if(type==='player'){rect(-10,-9,20,24,'#58785e');rect(-8,-21,16,15,'#aac0a0');rect(-6,-15,12,9,'#d5b48b');rect(-11,12,8,9,'#8f9e78');rect(4,12,8,9,'#8f9e78');rect(13,-10,4,30,'#c0a471');rect(17,-6,3,22,'#775f43');rect(-8,-23,16,5,'#446c56');}else if(type==='boss'){rect(-27,-24,54,51,'#706875');rect(-21,-37,42,29,'#928782');rect(-30,-45,10,24,'#bca57e');rect(20,-45,10,24,'#bca57e');rect(-14,-24,9,5,'#ff836c');rect(6,-24,9,5,'#ff836c');rect(-12,2,24,13,'#ab7358');rect(-36,0,9,35,'#bfa784');}else{let c=s?.key?'#b75553':type==='archer'?'#a08fbd':type==='charger'?'#b2976f':type==='scatter'?'#ce8e70':'#839985';rect(-11,-12,22,27,c);rect(-8,-20,16,15,c);rect(-6,-13,4,4,'#eddda9');rect(3,-13,4,4,'#eddda9');rect(-12,13,8,7,'#48574c');rect(4,13,8,7,'#48574c');}ctx.restore();}
function draw(){ctx.clearRect(0,0,960,540);rect(0,0,960,540,'#11191b');for(let y=40;y<510;y+=30)for(let x=25;x<940;x+=35){let n=((x*17+y*31)%19);rect(x,y,34,29,n<5?'#283231':n<12?'#252e2d':'#222c2b');if(n<3)rect(x+4,y+20,12,2,'#354039');}for(let x=0;x<960;x+=48){rect(x,0,46,30,'#3c4742');rect(x+2,31,43,13,'#202927');rect(x,508,46,32,'#3c4742');}for(let y=35;y<510;y+=40){rect(0,y,25,38,'#3e4943');rect(935,y,25,38,'#3e4943');}for(const x of [85,875])for(const y of [82,455]){rect(x-8,y,16,20,'#515b4d');rect(x-4,y-12,8,15,'#cf9854');rect(x-2,y-17,5,12,'#f0cc7c');}
 if(!s){sprite(480,285,'player');return;}const r=room();for(let d=0;d<4;d++)if(neighbor(s,d)>=0){let x=d===1?931:d===3?0:440,y=d===0?0:d===2?505:235;rect(x,y,d%2?29:80,d%2?70:35,'#101b1b');if(r.type==='boss'&&r.enemies.length)rect(x,y,d%2?20:80,d%2?70:20,'#895c46');}
 if(['up','down','exit','fountain','treasure','shrine'].includes(r.type)||r.type==='boss'&&r.used&&s.floor<s.floors.length-1){rect(453,85,54,43,'#151f21');if(r.type==='shrine'){rect(465,88,30,38,r.used?'#50545a':'#9a88bb');text(r.used?'사용한 신전':'고대신의 신전',480,76);}else if(r.type==='fountain'){rect(456,100,48,25,'#667c76');rect(462,98,36,18,r.used?'#34423e':'#68b4ac');text(r.used?'메마른 샘':'요정의 샘물',480,76);}else if(r.type==='treasure'){rect(463,95,34,24,r.used?'#4f4b36':'#b69854');rect(478,99,5,9,'#ead18d');text(r.used?'빈 상자':'보물 상자',480,76);}else{for(let i=0;i<5;i++)rect(457+i*3,89+i*7,46-i*6,4,'#8a9380');text(r.type==='exit'?(s.key?'탈출구':'봉쇄된 출구'):r.type==='down'?'↓ '+s.floor+'층':'↑ '+(s.floor+2)+'층',480,76);}}
 drawObstacles(ctx,r.obstacles);
 r.enemies.forEach(e=>{if(e.chargeAngle!==undefined&&e.cd>=.45){ctx.strokeStyle='#e2b16e';ctx.setLineDash([7,5]);ctx.beginPath();ctx.moveTo(e.x,e.y);ctx.lineTo(e.x+Math.cos(e.chargeAngle)*120,e.y+Math.sin(e.chargeAngle)*120);ctx.stroke();ctx.setLineDash([]);}if(e.type==='ricochet'&&e.cd<.65){ctx.strokeStyle='#dd9973';ctx.beginPath();ctx.arc(e.x,e.y,e.type==='boss'?43:26,0,Math.PI*2);ctx.stroke();}if(e.type!=='brute')sprite(e.x,e.y,e.type);drawEnemyDetails(ctx,e);if(e.variant==='prism')drawPrism(ctx,e,r.obstacles);drawPattern(ctx,e);drawRanged(ctx,e,r.obstacles);if(e.burn>0)rect(e.x-17,e.y-8,4,10,'#ed9a55');if(e.slow>0)rect(e.x+14,e.y-8,4,10,'#91d0e3');rect(e.x-15,e.y-30,30,3,'#131b1b');rect(e.x-15,e.y-30,30*Math.max(0,e.hp/e.max),3,s.key?'#d7766b':'#a7ad7b');});if(s.invulnerable<=0||Math.floor(s.invulnerable*20)%2===0)sprite(s.player.x,s.player.y,'player');bullets.forEach(b=>rect(b.x-3,b.y-2,b.enemy?7:10,4,b.ricochet?'#74e1dd':b.enemy?'#e88373':s.player.split&&s.player.pierce?'#8fe0cd':'#e6d392'));fx.forEach(f=>{ctx.strokeStyle=f.color;ctx.lineWidth=3;ctx.beginPath();if(f.toX!==undefined){ctx.moveTo(f.x,f.y);ctx.lineTo(f.toX,f.toY);}else ctx.arc(f.x,f.y,f.r*(1-f.t),0,Math.PI*2);ctx.stroke();});
 drawMinimap(ctx,s.floors[s.floor],r);if(s.key){ctx.strokeStyle='#b74c4866';ctx.lineWidth=8;ctx.strokeRect(4,4,952,532);}const boss=r.enemies.find(e=>e.type==='boss');if(boss){rect(280,27,400,7,'#182120');rect(280,27,400*boss.hp/boss.max,7,'#b67864');text(boss.variant==='prism'?'프리즘의 수호자':'녹슨 탑의 파수꾼',480,20,'#d6bfa1',11);}
 $('floor').textContent=`${s.floor+1}층 · ${['잊힌 돌의 전당','파수꾼의 회랑','고대신의 서고','프리즘의 왕좌'][s.floor]}`;$('phase').textContent=s.key?'THE FRENZY / 귀환':'THE ASCENT / 탐험';$('health').textContent=`HP ${Math.ceil(s.player.hp)} / ${s.player.max}`;$('level').textContent=`LV ${s.player.level} · XP ${s.player.xp}/${xpRequired(s.player.level)}`;$('timer').textContent=timeString(s.elapsed);$('objective').textContent=s.key?'같은 길을 따라 1층 출구로 귀환하세요.':s.floor===s.floors.length-1?'최상층 보스를 처치하고 열쇠를 획득하세요.':s.floor%2?'보스를 처치하고 위층 계단을 여세요.':'위층 계단을 탐색하세요.';$('potion').textContent=`물약 ${s.player.potions} · Q`;$('skill').hidden=mode==='title'||!ultimateUnlocked(s.player);$('skill').disabled=s.skill>0;$('dodge').disabled=s.dodge>0;$('skill').textContent=s.skill>0?`화살비 ${s.skill.toFixed(1)}s`:'화살비 · F';$('dodge').textContent=s.dodge>0?`회피 ${s.dodge.toFixed(1)}s`:'회피 · SPACE';let i=interaction();$('interact').hidden=!i||paused;if(i)$('interact').textContent=i[0]+' · E';
}
button('bag',bag);button('pause',()=>mode==='pause'?resume():pause());button('potion',potion);button('skill',skill);button('dodge',dodge);button('interact',interact);
window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();if(e.repeat)return;keys.add(k);if(k==='escape'){mode==='pause'||mode==='bag'?resume():pause();}if(k==='i')mode==='bag'?resume():bag();if(!paused){if(k==='q')potion();if(k==='f')skill();if(k===' ')dodge();if(k==='e')interact();}});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();axis={x:0,y:0};if(!paused)pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){if(!paused)pause();save();}});window.addEventListener('pagehide',save);
let pointer=null;const stick=$('stick');function stickMove(e){const b=stick.getBoundingClientRect(),x=(e.clientX-b.left-b.width/2)/30,y=(e.clientY-b.top-b.height/2)/30,n=Math.max(1,Math.hypot(x,y));axis={x:x/n,y:y/n};stick.firstElementChild.style.transform=`translate(${axis.x*24}px,${axis.y*24}px)`;}stick.addEventListener('pointerdown',e=>{if(pointer!==null)return;pointer=e.pointerId;stick.setPointerCapture(pointer);stickMove(e);});stick.addEventListener('pointermove',e=>{if(e.pointerId===pointer)stickMove(e);});for(const event of ['pointerup','pointercancel','lostpointercapture'])stick.addEventListener(event,()=>{pointer=null;axis={x:0,y:0};stick.firstElementChild.style.transform='';});
function frame(now){let dt=Math.min(.04,(now-last)/1000);last=now;update(dt);draw();requestAnimationFrame(frame);}title();requestAnimationFrame(frame);

