import test from 'node:test';import assert from 'node:assert/strict';
import {newRun,currentRoom} from './engine.js';import {skills,levelChoices,applyLevelReward,consumeLevelChoice,rerollSkills} from './progression.js';import {encodeSave,parseSave} from './storage.js';import {observeGrowth,tickBossRecord,completeBossRecord,growthRecordMarkup} from './growth-records.js';import {ensureMetrics,enterRoom,stepRun} from './simulation.js';
function exhausted(){const s=newRun(42);s.player.mainSkill='frost';for(const k of skills)s.player[k.id]=['fire','poison','chain'].includes(k.id)?0:k.max;s.player.level=30;s.pendingLevels=1;s.levelQueue=[30];return s;}
test('exhausted skill pool provides saved repeatable growth choices with real benefits',()=>{let s=exhausted();assert.deepEqual(levelChoices(s).map(k=>k.id),['growthPower','growthHealth','growthHaste']);s=parseSave(encodeSave(s));assert.equal(rerollSkills(s),false);assert.equal(s.rerolls??1,1);assert.equal(levelChoices(s).length,3);const before=s.player.damage;assert.ok(applyLevelReward(s,'growthPower'));assert.equal(s.player.damage,before+2);consumeLevelChoice(s);assert.equal(applyLevelReward(s,'growthPower'),false);for(const [id,field,amount] of [['growthHealth','max',1],['growthHaste','bonusAttack',.03]]){s=exhausted();levelChoices(s);const n=s.player[field]||0;assert.ok(applyLevelReward(s,id));assert.equal(s.player[field],n+amount);assert.doesNotThrow(()=>parseSave(encodeSave(s)));}});
test('normal skill pool and guaranteed ultimate take precedence over fallback rewards',()=>{const s=newRun(7);s.player.mainSkill='frost';assert.ok(levelChoices(s).every(k=>!k.growth));const max=exhausted();max.player.ultimate=0;max.player.level=10;max.levelQueue=[10];assert.deepEqual(levelChoices(max).map(k=>k.id),['ultimate']);assert.equal(applyLevelReward(max,'growthPower'),false);});
test('growth rewards respect stat caps',()=>{const s=exhausted();s.player.damage=9999;s.player.max=1000;s.player.bonusAttack=99.99;assert.deepEqual(levelChoices(s).map(k=>k.id),['growthPower','growthHaste']);applyLevelReward(s,'growthPower');assert.equal(s.player.damage,10000);applyLevelReward(s,'growthHaste');assert.equal(s.player.bonusAttack,100);});
test('growth snapshots are recorded once per floor and direction and survive reload',()=>{let s=newRun(5);ensureMetrics(s);enterRoom(s);s.player.level=8;observeGrowth(s);assert.equal(s.metrics.growthEntries.length,1);assert.equal(s.metrics.growthEntries[0].level,1);s.key=true;observeGrowth(s);assert.equal(s.metrics.growthEntries.length,2);s=parseSave(encodeSave(s));assert.equal(s.metrics.growthEntries[1].level,8);assert.match(growthRecordMarkup(s),/하강/);s.metrics.growthEntries.push({...s.metrics.growthEntries[0]});assert.throws(()=>parseSave(encodeSave(s)));});
test('boss record excludes dormant rooms and descent, accumulates through reload and completes once',()=>{let s=newRun(5);ensureMetrics(s);tickBossRecord(s,currentRoom(s),10);assert.equal(s.metrics.bossRecords,undefined);s.floor=1;s.room=s.floors[1].findIndex(r=>r.type==='boss');tickBossRecord(s,currentRoom(s),2);s=parseSave(encodeSave(s));tickBossRecord(s,currentRoom(s),3);assert.equal(s.metrics.bossRecords[0].seconds,5);completeBossRecord(s);tickBossRecord(s,currentRoom(s),9);assert.equal(s.metrics.bossRecords[0].seconds,5);assert.ok(s.metrics.bossRecords[0].complete);s.metrics.bossRecords[0].seconds=-1;assert.throws(()=>parseSave(encodeSave(s)));});
test('simulation observes growth without retroactively creating missing floor records',()=>{const s=newRun(9);s.floor=6;s.room=0;s.player.mainSkill='frost';s.attack=999;s.invulnerable=999;stepRun(s,.01);assert.equal(s.metrics.growthEntries.length,1);assert.equal(s.metrics.growthEntries[0].floor,6);assert.doesNotThrow(()=>parseSave(encodeSave(s)));});

test('restoring excludes capped growth candidates and persists the corrected list',()=>{let s=exhausted();levelChoices(s);s.player.damage=10000;s=parseSave(encodeSave(s));assert.deepEqual(levelChoices(s).map(k=>k.id),['growthHealth','growthHaste']);assert.deepEqual(s.choices,['growthHealth','growthHaste']);assert.equal(applyLevelReward(s,'growthPower'),false);assert.ok(applyLevelReward(s,'growthHealth'));});
test('fully stale saved choices rebuild without rerolling ultimate eligibility or consuming a level',()=>{const s=exhausted();s.player.ultimate=0;s.choices=['growthPower'];s.player.damage=10000;s.ultimateOffer=false;s.ultimateMilestones=[5,10];const before=s.pendingLevels;assert.deepEqual(levelChoices(s,()=>{throw Error('must not reroll ultimate');}).map(k=>k.id),['growthHealth','growthHaste']);assert.equal(s.pendingLevels,before);assert.deepEqual(s.ultimateMilestones,[5,10]);});
