import test from 'node:test';import assert from 'node:assert/strict';
import {newRun,currentRoom} from './engine.js';import {lightningImpact,tickThunder,thunderDamage} from './lightning.js';import {hitEnemy} from './progression.js';import {encodeSave,parseSave} from './storage.js';import {ensureMetrics} from './simulation.js';
const enemy=(id,x=300+id*100)=>({id,type:'archer',x,y:250,hp:1000,max:1000,cd:999,balanceVersion:1});
function run(level=3){const s=newRun(55);s.player.chain=level;s.player.mainSkill='chain';s.player.damage=100;s.player.x=100;s.player.y=250;const r=currentRoom(s);r.obstacles=[];r.enemies=Array.from({length:6},(_,i)=>enemy(i));ensureMetrics(s);return s;}
test('lightning levels increase first target damage and chain power with 80 percent retention',()=>{for(let chain=1;chain<=3;chain++){const enemies=Array.from({length:5},(_,i)=>enemy(i));lightningImpact({damage:100,chain,x:100,y:250},enemies[0],enemies);assert.ok(Math.abs(1000-enemies[0].hp-[15,25,35][chain-1])<1e-8);for(let i=1;i<=chain;i++)assert.ok(Math.abs(1000-enemies[i].hp-[45,55,65][chain-1]*.8**(i-1))<1e-8);assert.equal(enemies[chain+1].hp,1000);}});
test('lightning branches provide strong single target and sustained five-target chain',()=>{for(const branch of ['surge','web']){const enemies=Array.from({length:6},(_,i)=>enemy(i));lightningImpact({damage:100,chain:3,x:100,y:250,evolutions:{chain:branch}},enemies[0],enemies);assert.equal(1000-enemies[0].hp,branch==='surge'?75:35);if(branch==='surge'){assert.equal(enemies[1].hp,880);assert.equal(enemies[2].hp,1000);}else assert.ok(Math.abs(1000-enemies[5].hp-65*.9**4)<1e-8);}});
test('thunder strikes exactly skill-level distinct targets every three seconds without chained effects',()=>{for(const level of [1,2,3]){const s=run(level),r=currentRoom(s);assert.equal(tickThunder(s,2.99).length,0);const fx=tickThunder(s,.01);assert.equal(fx.length,level);assert.equal(new Set(fx.map(f=>f.x)).size,level);assert.equal(r.enemies.filter(e=>e.hp===900).length,level);assert.equal(s.metrics.damageDealt,100*level);assert.equal(tickThunder(s,.01).length,0);}});
test('single boss receives one thunder hit and untargetable enemies are excluded',()=>{const s=run(),r=currentRoom(s);r.enemies=[{...enemy(0),type:'boss'}, {...enemy(1),phase:'splitJump'}, {...enemy(2),spawnGrace:1},enemy(3,1000)];assert.equal(tickThunder(s,3).length,1);assert.equal(r.enemies[0].hp,900);assert.ok(r.enemies.slice(1).every(e=>e.hp===1000));});
test('thunder damage matches normal direct arrow with relic and evolution modifiers, excludes lightning bonus',()=>{const s=run(),p=s.player;p.relics=['hunter'];p.power=3;p.split=1;p.pierce=2;p.evolutions={pierce:'depth',haste:'tempo'};const e={...enemy(0),type:'boss'},copy=structuredClone(e),expected=thunderDamage(p,e);hitEnemy({...p,chain:0},copy,[copy],[],1,false);assert.ok(Math.abs(1000-copy.hp-expected)<1e-8);});
test('thunder timer and random targets continue identically after save and damage telemetry excludes overkill',()=>{const s=run();tickThunder(s,1.5);const copy=parseSave(encodeSave(s));assert.deepEqual(tickThunder(s,1.5),tickThunder(copy,1.5));assert.deepEqual(currentRoom(s).enemies,currentRoom(copy).enemies);currentRoom(s).enemies=[{...enemy(0),hp:1}];const before=s.metrics.damageDealt;tickThunder(s,3);assert.equal(s.metrics.damageDealt-before,1);s.thunderClock=4;assert.throws(()=>encodeSave(s));});
