import {CROSSBOW} from './combat-tuning.js';
import {hasRelic,relicStat,hexFactor} from './relics.js';
import {bindDefenses,enemyDamageFactor} from './enemy-defense.js';
import {moveBody,segmentBlocked} from './terrain.js';
const grounded=e=>e.hp>0&&!['air','splitJump'].includes(e.phase)&&e.attackPhase!=='leap';
export const passivePower=p=>p.damage*(1+.12*(p.power||0)+relicStat(p,'damage'))*hexFactor(p,'damage');
function deal(s,e,value,source){if(e.hp<=0)return;const hp=e.hp;e.hp-=value*enemyDamageFactor(e,source);if(e.hp<=0)e.passiveKilled=true;if(s.metrics)s.metrics.damageDealt+=hp-Math.max(0,e.hp);}
function shoot(s,from,target,kind,damage){const a=Math.atan2(target.y-from.y,target.x-from.x);s.projectiles.push({x:from.x,y:from.y,vx:Math.cos(a)*420,vy:Math.sin(a)*420,life:2,enemy:false,passive:kind,passiveDamage:damage,homing:kind!=='turret',hit:[],pierce:0,elemental:false});return a;}
export function passiveHit(s,b,e){const r=s.floors[s.floor][s.room];bindDefenses(r.enemies);const before=Math.max(0,e.hp);deal(s,e,b.passiveDamage,b);if(b.passive==='turret'&&s.metrics)s.metrics.ultimateDamage=(s.metrics.ultimateDamage||0)+before-Math.max(0,e.hp);if(b.passive==='sunFairy'&&e.hp>0)e.fairyBurn={time:3,dps:b.passiveDamage*.5*(1+relicStat(s.player,'dot'))};if(b.passive==='snowFairy'&&e.hp>0){e.slowFactor=Math.min(e.slow>0?(e.slowFactor??1):1,.75);e.slow=Math.max(e.slow||0,2);}if(b.passive==='stormFairy'){const other=r.enemies.filter(n=>n!==e&&grounded(n)&&Math.hypot(n.x-e.x,n.y-e.y)<150&&!segmentBlocked(e,n,r.obstacles)).sort((a,c)=>Math.hypot(a.x-e.x,a.y-e.y)-Math.hypot(c.x-e.x,c.y-e.y))[0];if(other){deal(s,other,b.passiveDamage*.5,e);r.passiveArcs??=[];r.passiveArcs.push({x:e.x,y:e.y,toX:other.x,toY:other.y,time:.2});}}}
export function tickPassives(s,dt){const r=s.floors[s.floor][s.room],p=s.player;bindDefenses(r.enemies);const power=passivePower(p),visible=(from,range=360)=>r.enemies.filter(e=>grounded(e)&&Math.hypot(e.x-from.x,e.y-from.y)<=range&&!segmentBlocked(from,e,r.obstacles,3)).sort((a,b)=>Math.hypot(a.x-from.x,a.y-from.y)-Math.hypot(b.x-from.x,b.y-from.y));s.passiveClocks??={};
 for(const [id,scale] of [['sunFairy',.4],['snowFairy',.5],['stormFairy',.8]])if(hasRelic(p,id)){s.passiveClocks[id]=Math.max(0,(s.passiveClocks[id]??1.5)-dt);const target=visible(p)[0];if(target&&s.passiveClocks[id]<=1e-9){const i=['sunFairy','snowFairy','stormFairy'].indexOf(id),from={x:Math.max(35,Math.min(925,p.x-24+i*24)),y:Math.max(50,p.y-40)};shoot(s,segmentBlocked(p,from,r.obstacles,3)?p:from,target,id,power*scale*(1+relicStat(p,'element')));s.passiveClocks[id]=1.5;}}
 for(const e of r.enemies){if(e.fairyBurn){deal(s,e,Math.min(dt,e.fairyBurn.time)*e.fairyBurn.dps);e.fairyBurn.time=Math.max(0,e.fairyBurn.time-dt);if(!e.fairyBurn.time)delete e.fairyBurn;}e.orbitHit=Math.max(0,(e.orbitHit||0)-dt);}
 if(hasRelic(p,'orbitBlades'))for(const e of r.enemies)if(grounded(e)&&!e.orbitHit){for(let i=0;i<2;i++){const a=s.elapsed*2.5+i*Math.PI,point={x:p.x+Math.cos(a)*65,y:p.y+Math.sin(a)*65};if(Math.hypot(e.x-point.x,e.y-point.y)<30&&!segmentBlocked(p,e,r.obstacles)){deal(s,e,power*.5,point);e.orbitHit=.6;break;}}}
 if(hasRelic(p,'voidBell')){s.passiveClocks.voidBell=Math.max(0,(s.passiveClocks.voidBell??12)-dt);const target=visible(p)[0];if(target&&s.passiveClocks.voidBell<=1e-9){r.voidPull={x:target.x,y:target.y,time:1};s.passiveClocks.voidBell=12;}}
 if(r.voidPull){const z=r.voidPull;for(const e of r.enemies)if(grounded(e)&&e.type!=='boss'&&Math.hypot(e.x-z.x,e.y-z.y)<180){const a=Math.atan2(z.y-e.y,z.x-e.x),step=Math.min(180*dt,Math.hypot(z.x-e.x,z.y-e.y));moveBody(e,Math.cos(a)*step,Math.sin(a)*step,r.obstacles,19);}z.time-=dt;if(z.time<=0)r.voidPull=null;}
 for(const t of r.turrets||[]){const active=Math.min(dt,t.time);t.time=Math.max(0,t.time-dt);t.clock=Math.max(0,t.clock-active);const target=visible(t,CROSSBOW.range)[0];if(target&&t.clock<=1e-9&&t.time>0){t.aim=shoot(s,t,target,'turret',power*CROSSBOW.damage*(1+relicStat(p,'ultimateDamage')));t.clock=CROSSBOW.interval;}}r.turrets=(r.turrets||[]).filter(t=>t.time>0);r.passiveArcs=(r.passiveArcs||[]).map(a=>({...a,time:a.time-dt})).filter(a=>a.time>0);
}
export function drawPassives(ctx,s){const r=s.floors[s.floor][s.room],p=s.player;ctx.save();if(r.arrowRain){const z=r.arrowRain;ctx.fillStyle='#80cfff35';ctx.strokeStyle='#b3e6ff';ctx.beginPath();ctx.arc(z.x,z.y,z.r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.save();ctx.clip();ctx.strokeStyle='#dbf4ff99';for(let i=0;i<32;i++){const x=z.x-280+(i*89)%560,y=z.y-280+((i*71+z.elapsed*380)%560);ctx.beginPath();ctx.moveTo(x,y-18);ctx.lineTo(x,y+9);ctx.lineTo(x-4,y+3);ctx.moveTo(x,y+9);ctx.lineTo(x+4,y+3);ctx.stroke();}ctx.restore();}
 for(const t of r.turrets||[]){if(t.time<3&&Math.floor(t.time*7)%2===0)continue;ctx.save();ctx.translate(t.x,t.y);ctx.fillStyle='#a48d63';ctx.fillRect(-12,5,24,12);ctx.rotate(t.aim);ctx.strokeStyle='#d5ba78';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(-8,-15);ctx.lineTo(6,0);ctx.lineTo(-8,15);ctx.moveTo(-12,0);ctx.lineTo(20,0);ctx.stroke();ctx.strokeStyle='#f3e4b4';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(-8,-15);ctx.lineTo(-8,15);ctx.stroke();ctx.restore();}
 if(hasRelic(p,'orbitBlades'))for(let i=0;i<2;i++){const a=s.elapsed*2.5+i*Math.PI;ctx.save();ctx.translate(p.x+Math.cos(a)*65,p.y+Math.sin(a)*65);ctx.rotate(a);ctx.fillStyle='#eaf4ff';ctx.fillRect(-3,-15,6,25);ctx.fillStyle='#c6a35b';ctx.fillRect(-7,8,14,4);ctx.restore();}
 for(const [i,id] of ['sunFairy','snowFairy','stormFairy'].entries())if(hasRelic(p,id)){ctx.fillStyle=['#ff993f','#99ddff','#ffe16a'][i];const x=p.x-24+i*24,y=p.y-40+Math.sin(s.elapsed*3+i)*4;ctx.fillRect(x-3,y-3,6,6);ctx.fillStyle='#ffffff77';ctx.fillRect(x-8,y-2,4,4);ctx.fillRect(x+4,y-2,4,4);}
 if(r.voidPull){ctx.strokeStyle='#d8a5ff';ctx.beginPath();ctx.arc(r.voidPull.x,r.voidPull.y,180*r.voidPull.time,0,Math.PI*2);ctx.stroke();}for(const a of r.passiveArcs||[]){ctx.strokeStyle='#ffe16a';ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(a.toX,a.toY);ctx.stroke();}ctx.restore();}
