import test from 'node:test';
import assert from 'node:assert/strict';
import {newRun} from './engine.js';
import {discoveredRooms,migrateRun,skillChoices,applySkill,combinations,hitEnemy,tickEffects,skills} from './progression.js';
test('minimap excludes unseen rooms and their bounds, including after reload',()=>{const rooms=[{x:0,y:0,seen:true},{x:-100,y:40,seen:false}];assert.deepEqual(discoveredRooms(rooms),[rooms[0]]);rooms[1].seen=true;assert.equal(discoveredRooms(JSON.parse(JSON.stringify(rooms))).length,2);});
test('old saves gain modest speed increase without losing build or map',()=>{const s=newRun();s.player.speed=155;s.player.split=2;delete s.player.fire;const floors=JSON.stringify(s.floors);migrateRun(s);assert.equal(s.player.speed,174);assert.equal(s.player.split,2);assert.equal(s.player.fire,0);assert.equal(JSON.stringify(s.floors),floors);});
test('offers are unique, exclude capped skills, and combinations activate only with both skills',()=>{const p=newRun().player;for(let i=0;i<50;i++){const choices=skillChoices(p);assert.equal(choices.length,3);assert.equal(new Set(choices.map(k=>k.id)).size,3);}applySkill(p,'fire');assert.equal(combinations(p).length,0);applySkill(p,'repeat');assert.equal(combinations(p)[0].name,'속성 연사');for(const k of skills)p[k.id]=k.max;assert.equal(skillChoices(p).length,0);assert.equal(applySkill(p,'split'),false);});
test('fire splashes on primary hits and low level has no lingering burn',()=>{const p={damage:10,fire:1},e={x:0,y:0,hp:200},near={x:10,y:0,hp:200};hitEnemy(p,e,[e,near]);assert.ok(Math.abs(near.hp-180.2)<1e-9);hitEnemy(p,e,[e,near]);assert.ok(Math.abs(near.hp-160.4)<1e-9);hitEnemy(p,e,[e,near]);assert.ok(Math.abs(near.hp-140.6)<1e-9);const hp=e.hp;tickEffects(e,4);assert.equal(e.hp,hp);assert.equal(e.slow,0);assert.equal(e.blastCooldown,0);});
test('lightning chains to distinct nearby enemies and thunderstorm increases range',()=>{const p={damage:10,chain:2,haste:1},a={x:0,y:0,hp:100},b={x:170,y:0,hp:100},c={x:340,y:0,hp:100};assert.equal(hitEnemy(p,a,[a,b,c]).length,2);assert.equal(a.hp,87.5);assert.equal(b.hp,94.5);assert.equal(c.hp,95.6);});
