import test from 'node:test';
import assert from 'node:assert/strict';
import {advanceRicochet,beamEnd,updateRanged} from './ranged.js';
import {newRun} from './engine.js';
test('fast rounds bounce once then disappear at the next wall',()=>{const b={x:920,y:200,vx:330,vy:0,bounces:1,life:10};advanceRicochet(b,.1,[],{x:0,y:0});assert.ok(b.vx<0);assert.equal(b.bounces,0);advanceRicochet(b,3,[],{x:0,y:0});assert.equal(b.life,0);});
test('cover absorbs fast bullets and swept collision detects crossed player',()=>{const b={x:100,y:200,vx:330,vy:0,bounces:1,life:5};assert.equal(advanceRicochet(b,.5,[{x:140,y:180,w:5,h:40}],{x:200,y:200}),false);assert.equal(b.life,0);const c={...b,life:5,x:100};assert.equal(advanceRicochet(c,.5,[],{x:200,y:200}),true);});
test('laser aim stays fixed, survives save, and cover stops beam and damage',()=>{let e={x:100,y:200,type:'laser',cd:0},p={x:500,y:200};const cover=[{x:300,y:150,w:70,h:100}];updateRanged(e,p,cover,.01,[]);assert.equal(e.phase,'aim');assert.equal(e.aim,0);p.y=300;updateRanged(e,p,cover,.5,[]);assert.equal(e.aim,0);e=JSON.parse(JSON.stringify(e));p.y=200;assert.equal(updateRanged(e,p,cover,.71,[]),0);assert.equal(e.phase,'beam');assert.ok(beamEnd(e,cover).x<300);});
test('laser damages only once per burst and can be avoided by walking',()=>{const e={x:100,y:200,type:'laser',cd:0},p={x:400,y:200};updateRanged(e,p,[],.01,[]);assert.equal(updateRanged(e,p,[],1.21,[]),18);assert.equal(updateRanged(e,p,[],.05,[]),0);const f={x:100,y:200,type:'laser',cd:0};updateRanged(f,p,[],.01,[]);p.y+=100;assert.equal(updateRanged(f,p,[],1.21,[]),0);});
test('ricochet fires a fixed symmetric pair only after warning',()=>{const e={x:100,y:200,type:'ricochet',cd:0},bullets=[];updateRanged(e,{x:500,y:200},[],.01,bullets);assert.equal(bullets.length,0);updateRanged(e,{x:500,y:300},[],.81,bullets);assert.equal(bullets.length,2);assert.equal(bullets[0].vy,-bullets[1].vy);assert.ok(Math.hypot(bullets[0].vx,bullets[0].vy)>330);});
