import test from 'node:test';import assert from 'node:assert/strict';
import {newRun,currentRoom} from './engine.js';import {stepRun,collisionTime,enterRoom} from './simulation.js';import {encodeSave,parseSave} from './storage.js';
function setup(){const s=newRun(42);s.attack=100;s.player.x=100;s.player.y=200;s.projectiles=[];currentRoom(s).obstacles=[];currentRoom(s).enemies=[];return s;}
test('swept hit detects crossed targets and arrows hit nearest enemy first',()=>{assert.ok(collisionTime({x:0,y:0},{x:100,y:0},{x:50,y:0},5)<.5);const s=setup();s.player.damage=20;currentRoom(s).enemies=[{id:2,type:'chaser',x:220,y:200,hp:50,max:50,cd:3},{id:1,type:'chaser',x:180,y:200,hp:50,max:50,cd:3}];s.projectiles=[{x:120,y:200,vx:1000,vy:0,life:1,enemy:false,pierce:0,hit:[]}];stepRun(s,.12);assert.equal(currentRoom(s).enemies[0].hp,50);assert.equal(currentRoom(s).enemies[1].hp,30);});
test('arrow hits target before wall but never enemy behind cover',()=>{const s=setup();currentRoom(s).obstacles=[{x:230,y:150,w:20,h:100}];currentRoom(s).enemies=[{id:0,type:'chaser',x:180,y:200,hp:100,max:100,cd:2},{id:1,type:'chaser',x:290,y:200,hp:100,max:100,cd:2}];s.projectiles=[{x:120,y:200,vx:1000,vy:0,life:1,enemy:false,pierce:3,hit:[]}];stepRun(s,.2);assert.ok(currentRoom(s).enemies[0].hp<100);assert.equal(currentRoom(s).enemies[1].hp,100);});
test('lethal hit cannot be reversed by same-frame kill recovery',()=>{const s=setup();s.player.hp=1;s.player.unique=true;s.player.leechKills=11;currentRoom(s).enemies=[{id:0,type:'chaser',x:300,y:200,hp:0,max:40,cd:3}];s.projectiles=[{x:110,y:200,vx:-100,vy:0,life:1,enemy:true,hit:[]}];const result=stepRun(s,.1);assert.ok(result.events.includes('dead'));assert.equal(s.player.hp,0);assert.equal(s.kills,0);});
test('paused caller leaves pending projectiles exactly intact; save resumes identical simulation',()=>{const s=setup();s.player.x=480;s.player.y=300;currentRoom(s).enemies=[{id:0,type:'laser',x:200,y:200,hp:82,max:82,cd:.1,balanceVersion:1}];for(let i=0;i<45;i++)stepRun(s,1/60);const copy=parseSave(encodeSave(s));for(let i=0;i<60;i++){stepRun(s,1/60);stepRun(copy,1/60);}assert.deepEqual(copy,JSON.parse(JSON.stringify(s)));});
test('room entry clears stale attacks and gives bounded arrival time',()=>{const s=setup();currentRoom(s).enemies=[{id:0,type:'laser',x:200,y:200,hp:82,max:82,phase:'beam',phaseTime:.2,cd:0}];enterRoom(s);assert.equal(currentRoom(s).enemies[0].phase,null);assert.equal(s.entryGrace,.6);assert.equal(currentRoom(s).enemies[0].cd,.8);stepRun(s,1/60);assert.ok(s.entryGrace<.6);});
test('seed generates same maps and run randomness, with independent run identity',()=>{const a=newRun(1024),b=newRun(1024);assert.deepEqual(a.floors,b.floors);assert.notEqual(a.runId,b.runId);});
