import {enemyGuide} from './expedition.js';
import {relicInfo} from './relics.js';
import {eliteNames} from './elites.js';
import {evolutionSummary} from './evolutions.js';
import {safeHistory,RELEASE} from './storage.js';
import {timeString} from './engine.js';
export function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]);}
export function historyMarkup(storage){
 const rows=safeHistory(storage).reverse();
 return `<small>LOCAL RECORDS</small><h2>나의 도전 기록</h2><p>이 브라우저에 저장된 최근 30회 · 온라인 순위가 아닙니다.</p>${rows.length?`<div class="history-list">${rows.map(r=>`<article><b>${r.won?'탈출 성공':'도전 종료'} · ${timeString(r.time)}</b><span>${r.floor}층 · LV ${r.level} · 열쇠 ${r.key?'획득':'미획득'}</span><small>${escapeHtml(r.date?.slice(0,10)||'날짜 없음')} · ${escapeHtml(r.release||'이전 버전')}</small><small>분기 · ${evolutionSummary({evolutions:r.evolutions})}</small><small>유물 · ${relicInfo(r.relic)?.name||'없음'}${r.lastHit?' / 마지막 피격 · '+escapeHtml(r.lastHit.source):''}</small></article>`).join('')}</div>`:'<p>아직 기록이 없습니다.</p>'}<button id="closeInfo">돌아가기</button>`;
}
export function helpMarkup(){return `<small>FIELD GUIDE</small><h2>탑 탐험 안내</h2><div class="guide"><p><b>목표</b> 2·4층 보스로 위층을 열고, 6층 분열 슬라임을 모두 처치해 열쇠를 얻어 1층 출구로 돌아오세요. 일반방은 모두 처치할 필요가 없습니다.</p><p><b>이동</b> WASD·방향키 또는 왼쪽 조이스틱. 방 가장자리 중앙의 문으로 이동합니다. 공격은 가장 가까운 보이는 적을 자동 조준합니다.</p><p><b>성장</b> 첫 기술에서 화염·서리·독·번개 중 메인 하나를 고릅니다. 이후 선택한 메인과 보조를 조합합니다. 갈래·연속탄은 희귀, 유도는 유니크입니다. 서리는 3중첩에서 빙결합니다.</p><p><b>생존</b> Q 물약 2하트 · Space 회피 20초. 회피는 이동 방향, 멈춰 있으면 마지막 이동 방향으로 나갑니다. 장애물을 넘어가지는 못합니다.</p><p><b>성장</b> 레벨업에서 기술을 5번 선택하면 F 화살비가 해금됩니다. 조합은 자동으로 활성화됩니다. 보물방에서는 무기·생존·기술 중 하나만 고릅니다. 기술 3레벨에서 전투 분기를 선택하고, 화살비도 즉시형/영역형 중 선택합니다. 3층 신전에서 장비를 강화할 수 있습니다.</p><p><b>보스 유물</b> 중간 보스 처치 후 최대 3개 중 하나를 고릅니다. 장점과 단점이 있으며 한 개만 장착합니다. 교체할 때 재사용 대기시간은 초기화되지 않습니다.</p><p><b>원정 기록</b> 가방·일시정지·종료 화면에서 목격한 적, 최근 피격 10건과 층별 기록을 볼 수 있습니다. 이번 버전에서 시작한 도전은 종료 후 같은 지도에서 재도전할 수 있습니다.</p><p><b>체력</b> ♥ 현재 하트 · ♡ 잃은 하트 · ◇ 아직 얻지 않은 칸. 보호막 ◈ 준비는 공격 한 번 방어입니다. 음식은 안전한 방의 가방에서 예약하고 재개할 때 회복합니다.</p><p><b>독 공격</b> 점선 원은 착탄 예고, 초록 영역은 독 장판입니다. 꽃봉우리 장판은 2초 유지됩니다. 겹친 독은 중복 피해를 주지 않지만 머무르면 1초 간격으로 피해를 받습니다.</p><p><b>정예와 계약</b> 금빛 정예는 폭발·주변 피해 경감·추가 사격 중 한 특성을 가지며, 처치 시 물약 1개를 줍니다. ? 제단은 하트·물약 거래 또는 선택형 시련이며 대가를 확인하고 지나갈 수도 있습니다.</p><p><b>기록·저장</b> 가방·선택·일시정지·배경 전환 중 시간은 멈춥니다. 같은 브라우저에서 이어갈 수 있습니다. 한 도전은 한 탭에서만 진행하세요.</p><p><b>귀환</b> 내려갈수록 광폭화 적의 수와 탄막이 강해집니다. 지나온 방과 시설 상태는 유지됩니다. 사용하지 않은 샘물을 남겨두면 귀환에 도움이 됩니다. 미니맵은 방문한 방과 그 방의 문만 보여줍니다. 열쇠 획득 후 귀환 경로 버튼으로 최단/위험 회피 경로를 표시할 수 있습니다. 초록 방은 적 수가 적고, 붉은 방에는 포화 정예가 있습니다.</p></div><button id="closeInfo">돌아가기</button>`;}
export function downloadJSON(name,data){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function diagnostic(s,notes=''){return {release:RELEASE,createdAt:new Date().toISOString(),notes,run:s?{id:s.runId,seed:s.seed,status:s.status,floor:s.floor+1,room:s.room,time:s.elapsed,key:s.key,player:s.player,metrics:s.metrics,bestiary:s.bestiary,combatLog:s.combatLog,lastHit:s.lastHit}:null};}

export function journalMarkup(s){const discovered=Object.keys(enemyGuide).filter(k=>s.bestiary?.[k]);return '<small>EXPEDITION JOURNAL</small><h2>이번 원정 기록</h2><div class="guide"><p>시드 '+s.seed+' · 유물 '+(relicInfo(s.player.relic)?.name||'없음')+'</p><h3>층별 탐험</h3>'+s.floors.map((_,f)=>'<p>'+(f+1)+'층 · '+timeString(s.metrics?.floorTimes?.[f]||0)+' · 피해 '+(s.metrics?.floorDamage?.[f]||0)+'하트</p>').join('')+'<h3>최근 피격 / 보호막</h3>'+((s.combatLog||[]).slice().reverse().map(h=>'<p>'+timeString(h.time)+' · '+h.floor+'층 · '+escapeHtml(h.source)+' · '+(h.blocked?'보호막 방어':h.amount+'하트')+'</p>').join('')||'<p>아직 기록이 없습니다.</p>')+'<h3>목격한 적 '+discovered.length+'/'+Object.keys(enemyGuide).length+'</h3>'+discovered.map(k=>'<article><b>'+enemyGuide[k].name+'</b><p>'+enemyGuide[k].tip+'<br>처치 '+s.bestiary[k].kills+'회'+(k==='slime'?' (분열체 포함)':'')+' · 목격한 특성 '+(s.bestiary[k].traits.map(t=>eliteNames[t]).filter(Boolean).join(', ')||'일반')+'</p></article>').join('')+'<p>아직 만나지 않은 적은 표시하지 않습니다. 기록은 이번 도전의 관찰이며 과거 피격을 소급 추정하지 않습니다.</p></div><button id="closeJournal">돌아가기</button>';}
