import {growthRecordMarkup} from './growth-records.js';
import {enemyGuide} from './expedition.js';
import {relicInfo,relicSummary} from './relics.js';
import {eliteNames} from './elites.js';
import {evolutionSummary} from './evolutions.js';
import {safeHistory,RELEASE} from './storage.js';
import {timeString} from './engine.js';
export function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]);}
export function historyMarkup(storage){
 const rows=safeHistory(storage).reverse();
 return `<small>LOCAL RECORDS</small><h2>나의 도전 기록</h2><p>이 브라우저에 저장된 최근 30회 · 온라인 순위가 아닙니다.</p>${rows.length?`<div class="history-list">${rows.map(r=>`<article><b>${r.won?'탈출 성공':'도전 종료'} · ${timeString(r.time)}</b><span>${r.floor}층 · LV ${r.level} · 열쇠 ${r.key?'획득':'미획득'}</span><small>${escapeHtml(r.date?.slice(0,10)||'날짜 없음')} · ${escapeHtml(r.release||'이전 버전')}</small><small>분기 · ${evolutionSummary({evolutions:r.evolutions})}</small><small>유물 · ${relicSummary(r)}${r.lastHit?' / 마지막 피격 · '+escapeHtml(r.lastHit.source):''}</small></article>`).join('')}</div>`:'<p>아직 기록이 없습니다.</p>'}<button id="closeInfo">돌아가기</button>`;
}
export function helpMarkup(){return `<small>FIELD GUIDE</small><h2>탑 탐험 안내</h2><div class="guide"><p><b>목표</b> 2·4·6층 보스와 7층 정예 관문을 통과하고, 8층 타락한 왕을 처치해 열쇠를 얻어 1층 출구로 돌아오세요. 등반 중에는 방의 적을 전멸해야 출구가 열리고, 하강 시 미방문 방은 전멸해야 출구가 열립니다. 방문한 방의 30%는 열쇠수호자를 처치해야 열리며, 내려가는 계단은 방 전멸 후 봉인이 해제됩니다.</p><p><b>이동</b> WASD·방향키 또는 왼쪽 조이스틱. 방 가장자리 중앙의 문으로 이동합니다. 공격은 가장 가까운 보이는 적을 자동 조준합니다.</p><p><b>성장</b> 첫 기술에서 화염·서리·독·번개 중 메인 하나를 고릅니다. 이후 선택한 메인과 보조를 조합합니다. 갈래·연속탄은 희귀, 유도는 유니크입니다. 서리는 1/2/3/4레벨에서 4/3/2/2회 적중 시 빙결합니다. 중첩·빙결 상태 사망은 파편을 방출하며 4레벨 빙결 사망은 12갈래입니다.</p><p><b>생존</b> 몬스터 접촉은 1하트 피해이며 피격 후 0.65초 무적입니다. 돌진·내려찍기는 별도 공격 피해입니다. Q 물약 1하트 · 재사용 3초 · Space 점멸 10초. 점멸은 이동 방향, 멈춰 있으면 마지막 이동 방향으로 나갑니다. 장애물을 넘어가지는 못합니다.</p><p><b>성장</b> 궁극기는 5·10레벨에 미습득이면 확정 후보, 그 외 5레벨 이후 30% 확률로 후보에 등장합니다. 선택 후 화살비 또는 자동 저격 석궁을 고릅니다. 조합은 자동으로 활성화됩니다. 상자는 무작위 보상 또는 함정을 즉시 지급합니다. 기술 3레벨에서 전투 분기를 선택하고, 화살비는 반경 280에서 3회 타격, 석궁은 재사용 20초·유지 19초이며 최대 2대입니다. 3층 고대인의 신전은 정예 전투 후 두 주술 중 하나를 반드시 선택해야 합니다. 축복 10종·저주 5종 중 두 후보가 나오며 저주 둘이 나올 수도 있습니다.</p><p><b>보스 유물</b> 모든 보스 처치 후 최대 3개 중 하나를 골라 누적 소유합니다. 유물은 총 32종이며 모두 이로운 효과입니다. 유니크 6종은 낮은 확률로 등장합니다. 시련에서도 드물게 획득합니다. 정수는 사망 위치에 나타나고 가까이 가면 획득합니다. 하강 중에는 드랍 확률이 두 배입니다.</p><p><b>원정 기록</b> 가방·일시정지·종료 화면에서 목격한 적, 최근 피격 10건과 층별 기록을 볼 수 있습니다. 이번 버전에서 시작한 도전은 종료 후 같은 지도에서 재도전할 수 있습니다.</p><p><b>체력</b> 좌측 하단 도트 하트는 현재/최대 체력입니다. 빈 마름모 표시는 제거했습니다. 방패 아이콘 옆에 장비·오라 보호막의 준비 또는 충전 시간이 표시됩니다. 흰 실루엣은 오라 보호막 준비 상태입니다. 음식은 안전한 방의 가방에서 예약하고 재개할 때 회복합니다.</p><p><b>상층 편성</b> 7층에는 저격·인력·호위 등 6종 편성, 8층에는 근위대·균열 습격 등을 더한 9종 편성이 등장합니다. 지원몹은 방당 최대 1체입니다. 두 문지기 중 한 체를 쓰러뜨리면 남은 문지기가 격노합니다. 왕 처치 연출 중에도 귀환 버튼으로 바로 진행할 수 있습니다.</p><p><b>상층 전투</b> 돌진은 표시된 폭을 따라 이동하고, 고리 탄막의 초록 틈은 안전 방향입니다. 이중 테두리와 !! 2♥ 표시는 강공격입니다. 상단에서 경고음을 끌 수 있습니다. 왕의 체력 65%·30%에서 단계가 전환되고, 심판 마지막 내려찍기 후에는 긴 빈틈이 생깁니다. 성운 기사의 방패는 전방 직격을 줄이며 후방·장판·지속 피해로 공략할 수 있습니다. 별 운반체의 금빛 연결선은 공격 가속 대상을 표시합니다.</p><p><b>독 공격</b> 점선 원은 착탄 예고, 보라 영역은 몬스터 독 장판, 초록은 플레이어 독입니다. 꽃봉우리 장판은 2초 유지됩니다. 겹친 독은 중복 피해를 주지 않지만 머무르면 1초 간격으로 피해를 받습니다.</p><p><b>정예와 계약</b> 금빛 정예는 폭발·주변 피해 경감·추가 사격 중 한 특성을 가지며, 정예 처치 물약은 방당 최대 1개입니다. 보스가 소환한 정예는 보상을 주지 않습니다. ? 제단은 하트·물약 거래 또는 선택형 시련이며 대가를 확인하고 지나갈 수도 있습니다.</p><p><b>전투 HUD</b> 유물 아래 정수는 종류별 획득 개수와 누적 효과를 표시합니다. 좌측 상단 유물과 하단 스킬 아이콘에 마우스를 올리면 효과를 확인합니다. 하단 하늘색 바가 가득 차면 레벨업합니다. 미니맵 아래 DPS는 최근 5초 실제 피해를 5로 나눈 값이며 범위 피해를 포함합니다. 공격력에는 거리·적 체력 등 조건부 유물 효과를 포함하지 않습니다.</p><p><b>기록·저장</b> 가방·선택·일시정지·배경 전환 중 시간은 멈춥니다. 같은 브라우저에서 이어갈 수 있습니다. 한 도전은 한 탭에서만 진행하세요.</p><p><b>귀환</b> 내려갈수록 광폭화 적의 수와 탄막이 강해집니다. 지나온 방과 시설 상태는 유지됩니다. 사용하지 않은 샘물을 남겨두면 귀환에 도움이 됩니다. 샘물 단독 방은 30% 확률로 비어 있고, 나머지는 최대 3마리입니다. 샘물방 25%에는 상자가 함께 등장하며 일반방 편성으로 싸웁니다. 샘물과 상자는 전멸 후 각각 사용합니다. 미니맵은 방문한 방과 그 방의 문만 보여줍니다. 열쇠 획득 후 귀환 경로 버튼으로 최단/위험 회피 경로를 표시할 수 있습니다. 초록 방은 적 수가 적고, 붉은 방에는 포화 정예가 있습니다.</p></div><button id="closeInfo">돌아가기</button>`;}
export function downloadJSON(name,data){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function diagnostic(s,notes=''){return {release:RELEASE,createdAt:new Date().toISOString(),notes,run:s?{id:s.runId,seed:s.seed,status:s.status,floor:s.floor+1,room:s.room,time:s.elapsed,key:s.key,player:s.player,metrics:s.metrics,bestiary:s.bestiary,combatLog:s.combatLog,lastHit:s.lastHit}:null};}

export function journalMarkup(s){const discovered=Object.keys(enemyGuide).filter(k=>s.bestiary?.[k]);return '<small>EXPEDITION JOURNAL</small><h2>이번 원정 기록</h2><div class="guide"><p>시드 '+s.seed+' · 유물 '+(relicSummary(s.player))+'</p><h3>층별 탐험</h3>'+s.floors.map((_,f)=>'<p>'+(f+1)+'층 · '+timeString(s.metrics?.floorTimes?.[f]||0)+' · 피해 '+(s.metrics?.floorDamage?.[f]||0)+'하트</p>').join('')+growthRecordMarkup(s)+'<h3>최근 피격 / 보호막</h3>'+((s.combatLog||[]).slice().reverse().map(h=>'<p>'+timeString(h.time)+' · '+h.floor+'층 · '+escapeHtml(h.source)+' · '+(h.blocked?'보호막 방어':h.amount+'하트')+'</p>').join('')||'<p>아직 기록이 없습니다.</p>')+'<h3>목격한 적 '+discovered.length+'/'+Object.keys(enemyGuide).length+'</h3>'+discovered.map(k=>'<article><b>'+enemyGuide[k].name+'</b><p>'+enemyGuide[k].tip+'<br>처치 '+s.bestiary[k].kills+'회'+(k==='slime'?' (분열체 포함)':'')+' · 목격한 특성 '+(s.bestiary[k].traits.map(t=>eliteNames[t]).filter(Boolean).join(', ')||'일반')+'</p></article>').join('')+'<p>아직 만나지 않은 적은 표시하지 않습니다. 기록은 이번 도전의 관찰이며 과거 피격을 소급 추정하지 않습니다.</p></div><button id="closeJournal">돌아가기</button>';}

export function deathSummaryMarkup(s){
 const hits=(s.combatLog||[]).filter(h=>h.amount>0&&!h.blocked&&h.time<=s.elapsed&&s.elapsed-h.time<=15).slice(-3).reverse();
 if(!hits.length)return '<div class="guide"><p>사망 직전 15초 동안 기록된 피해가 없습니다.</p></div>';
 return '<div class="guide death-summary"><h3>사망 직전 피격 · 최근 15초</h3>'+hits.map((h,i)=>'<p><b>'+(i===0?'마지막 피해':Math.max(0,s.elapsed-h.time).toFixed(1)+'초 전')+'</b> · '+escapeHtml(h.source)+' · −'+h.amount+'♥</p>').join('')+'</div>';
}
