import test from 'node:test';import assert from 'node:assert/strict';
import {newRun,currentRoom} from './engine.js';import {stepRun} from './simulation.js';
import {challengeKing,startUpperAttack,updateUpper,tickUpperState,chooseKingAttack,judgmentStripe,pointInStripe} from './upper-floors.js';
import {encodeSave,parseSave} from './storage.js';import {hitEnemy} from './progression.js';import {passiveHit} from './passives.js';import {warningCount} from './tactics.js';
const foe=(type='starKnight',x=300,y=250)=>({id:0,type,x,y,hp:1000,max:1000,cd:0,balanceVersion:1});
function king(){const s=newRun(24);s.floor=7;s.room=s.floors[7].findIndex(r=>r.type==='boss');challengeKing(s);s.entryGrace=0;s.attack=999;s.invulnerable=999;return s;}
test('dash moves over time, damages only swept corridor, and stops before cover',()=>{const r={obstacles:[],enemies:[]},e=foe(),p={x:600,y:250},b=[];startUpperAttack(e,'dash',p,r);let hit=0;updateUpper(e,p,r,.85,b,n=>hit+=n);assert.equal(e.x,300);assert.ok(e.darkAttack.moving);updateUpper(e,{x:450,y:286},r,.16,b,n=>hit+=n);assert.equal(e.x,450);assert.equal(hit,0);updateUpper(e,{x:550,y:250},r,.16,b,n=>hit+=n);assert.equal(e.x,600);assert.equal(hit,9);assert.ok(e.opening>0);
 const wall={x:400,y:200,w:40,h:100};e.x=300;r.obstacles=[wall];startUpperAttack(e,'dash',p,r);assert.ok(e.darkAttack.tx<=375);});
test('saved dash resumes at identical coordinates and cannot damage twice',()=>{let s=king(),r=currentRoom(s),e=r.enemies[0];e.x=300;e.y=250;startUpperAttack(e,'dash',{x:650,y:250},r);updateUpper(e,s.player,r,.85,[],()=>{});updateUpper(e,{x:410,y:250},r,.12,[],()=>{});assert.ok(e.darkAttack.hit);let loaded=parseSave(encodeSave(s));const le=currentRoom(loaded).enemies[0];let damage=0;updateUpper(e,{x:600,y:250},r,.2,[],n=>damage+=n);updateUpper(le,{x:600,y:250},currentRoom(loaded),.2,[],n=>damage+=n);assert.equal(damage,0);assert.equal(e.x,le.x);assert.equal(e.y,le.y);});
test('ring locks its preview direction and all projectiles leave the visible safe gap',()=>{const e=foe('pulseTurret'),r={obstacles:[],enemies:[e]},p={x:600,y:250},b=[];e.escapeDepth=3;e.darkTurn=100;startUpperAttack(e,'ring',p,r);const aim=e.darkAttack.aim;assert.ok(Math.abs(aim)<=Math.PI);updateUpper(e,{x:50,y:100},r,.86,b,()=>{});assert.equal(b.length,19);for(const shot of b){const delta=Math.atan2(Math.sin(Math.atan2(shot.vy,shot.vx)-aim),Math.cos(Math.atan2(shot.vy,shot.vx)-aim));assert.ok(Math.abs(delta)>Math.PI/20);}});
test('king avoids empty melee at range and immediate pattern repeats',()=>{const e={...foe('boss'),variant:'king',hp:1000,max:1000};assert.equal(chooseKingAttack(e,{x:310,y:250}),'slash');for(let i=0;i<12;i++){e.darkTurn=i;const next=chooseKingAttack(e,{x:850,y:250});assert.notEqual(next,'slash');assert.notEqual(next,e.lastDarkAttack);e.lastDarkAttack=next;}});
test('both judgment orientations use the same rectangle for hit tests and previews',()=>{const e={...foe('boss'),variant:'king',hp:200,max:1000},r={obstacles:[],enemies:[e]};for(const expected of ['vertical','horizontal']){startUpperAttack(e,'judgment',{x:700,y:350},r);assert.equal(e.darkAttack.axis,expected);const z=judgmentStripe(e.darkAttack);assert.ok(pointInStripe({x:z.x+1,y:z.y+1},z));let damage=0;updateUpper(e,{x:z.x+z.w/2,y:z.y+z.h/2},r,1.1,[],n=>damage+=n);assert.equal(damage,18);const next=judgmentStripe(e.darkAttack);updateUpper(e,{x:next.x-1,y:next.y-1},r,.65,[],n=>damage+=n);assert.equal(damage,18);}});
test('judgment ends with a heavy marked strike and a long kneeling opening',()=>{const e={...foe('boss'),variant:'king',hp:200,max:1000},r={obstacles:[],enemies:[e]},p={x:900,y:480};startUpperAttack(e,'judgment',p,r);for(const dt of [1.1,.65,.65,.65])updateUpper(e,p,r,dt,[],()=>{});assert.ok(e.darkAttack.finisher);let damage=0;updateUpper(e,p,r,1.1,[],n=>damage+=n);assert.equal(damage,18);assert.equal(e.kneel,2.2);assert.equal(e.opening,2.2);});
test('phase changes clear attacks and enemy shots, freeze danger and round trip mid-transition',()=>{let s=king(),r=currentRoom(s),e=r.enemies[0];startUpperAttack(e,'dash',s.player,r);s.projectiles=[{x:480,y:300,vx:0,vy:0,enemy:true,life:2,hit:[]}];r.enemies.push({...foe('royalGuard'),id:1,x:s.player.x,y:s.player.y,summoned:true});e.hp=4500;s.invulnerable=0;const hp=s.player.hp;stepRun(s,.01);assert.equal(e.kingStage,2);assert.ok(e.kingTransition>1);assert.equal(e.darkAttack,undefined);assert.ok(!s.projectiles.some(b=>b.enemy));assert.equal(s.player.hp,hp);s=parseSave(encodeSave(s));for(let i=0;i<30;i++)stepRun(s,.02);assert.equal(s.player.hp,hp);});
test('summon timer runs during long openings and freeze with a visible one second portal',()=>{const s=king(),r=currentRoom(s),e=r.enemies[0];e.hp=4500;e.kingStage=2;e.opening=5;e.frozen=5;e.guardClock=.2;for(let i=0;i<11;i++)stepRun(s,.02);assert.ok(e.guardPortal);assert.equal(r.enemies.length,1);const copy=parseSave(encodeSave(s));for(let i=0;i<51;i++)stepRun(copy,.02);assert.equal(currentRoom(copy).enemies.length,2);assert.ok(currentRoom(copy).enemies[1].spawnGrace>0);});
test('attack flash expires during recovery and while frozen',()=>{const s=king(),e=currentRoom(s).enemies[0];e.darkFlash={kind:'slash',time:.18,x:480,y:180,tx:480,ty:300,aim:0,step:0};e.opening=2;e.frozen=2;for(let i=0;i<12;i++)stepRun(s,.02);assert.equal(e.darkFlash,undefined);assert.ok(e.opening>0);});
test('king and guards cap overlapping new warnings at two',()=>{const s=king(),r=currentRoom(s),e=r.enemies[0];r.enemies.push({...foe('royalGuard'),id:1},{...foe('royalGuard'),id:2});for(const n of r.enemies.slice(1))startUpperAttack(n,'slash',s.player,r);e.cd=0;updateUpper(e,s.player,r,.01,[],()=>{});assert.equal(e.darkAttack,undefined);assert.equal(warningCount(r),2);});
test('knight shield reduces frontal arrows and tower shots but not rear or damage over time',()=>{for(const [x,expected] of [[400,65],[200,100]]){const e=foe();e.darkAttack={kind:'slash',aim:0};hitEnemy({damage:100,x,y:250},e,[e],[],1,false);assert.equal(e.hp,1000-expected);}const s=king(),e=foe();currentRoom(s).enemies=[e];e.darkAttack={kind:'slash',aim:0};passiveHit(s,{x:400,y:250,passive:'turret',passiveDamage:100},e);assert.equal(e.hp,935);passiveHit(s,{x:200,y:250,passive:'turret',passiveDamage:100},e);assert.equal(e.hp,835);});
test('new state validation rejects malformed moving dash and summon portal',()=>{const s=king(),e=currentRoom(s).enemies[0];startUpperAttack(e,'dash',s.player,currentRoom(s));e.darkAttack.elapsed=10;assert.throws(()=>encodeSave(s));delete e.darkAttack.elapsed;e.guardPortal={x:480,y:300,time:10};assert.throws(()=>encodeSave(s));});
