import {readFile,mkdir} from 'node:fs/promises';import {join} from 'node:path';import {pathToFileURL} from 'node:url';import assert from 'node:assert/strict';
const {chromium}=await import(pathToFileURL(join(process.env.PLAYWRIGHT_PATH,'index.mjs')).href),browser=await chromium.launch({channel:'msedge',headless:true}),errors=[];const output=process.argv[2];await mkdir(output,{recursive:true});
try{for(const existing of [false,true]){
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await context.route(/^https?:\/\/transfer\.test\//,async route=>{const file=new URL(route.request().url()).pathname.slice(1)||'upgrade.html';if(!['upgrade.html','upgrade.js','upgrade-transfer.js','pixel-theme.css','pixel-font.woff2'].includes(file)){await route.abort();return;}await route.fulfill({body:await readFile(file),contentType:file.endsWith('.html')?'text/html':file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'font/woff2'});});
 const source=await context.newPage();source.on('pageerror',e=>errors.push(e.message));if(existing){await source.goto('https://transfer.test/upgrade.html');await source.evaluate(()=>localStorage.setItem('spirebound.run.v1','secure run'));}
 await source.goto('http://transfer.test/upgrade.html');await source.evaluate(()=>{localStorage.setItem('spirebound.run.v1','old run');localStorage.setItem('spirebound.run.v1.backup','old backup');localStorage.setItem('spirebound.history','[]');localStorage.setItem('spirebound.active-tab','must not transfer');});
 const popupEvent=source.waitForEvent('popup');await source.locator('#transfer').click();const target=await popupEvent;target.on('pageerror',e=>errors.push(e.message));await target.locator('#status').filter({hasText:'기록'}).waitFor();await source.getByText('옮기기가 완료되었습니다.',{exact:false}).waitFor();
 assert.equal(await target.evaluate(()=>localStorage.getItem('spirebound.run.v1')),existing?'secure run':'old run');assert.equal(await target.evaluate(()=>localStorage.getItem('spirebound.active-tab')),null);assert.equal(await source.evaluate(()=>localStorage.getItem('spirebound.run.v1')),'old run');
 await target.screenshot({path:join(output,`transfer-${existing?'existing':'new'}.png`)});await context.close();
}assert.deepEqual(errors,[]);console.log('HTTP to HTTPS popup transfer verified; fresh and existing saves preserved');}finally{await browser.close();}
