import {attackProfile} from '../../src/combat/balance.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {newRun,currentRoom} from '../../src/game/engine.js';
import {challengeCommander,updateCommander,resetCommanderAttack} from '../../src/combat/commander.js';
import {challengeKing,startUpperAttack,updateUpper} from '../../src/combat/upper-floors.js';
import {encodeSave,parseSave} from '../../src/persistence/storage.js';
import {advanceRicochet} from '../../src/combat/ranged.js';
function commander(phase=1,legacy=false){const s=newRun(72,{campaign:'expanded'});if(legacy){s.generationVersion=30;s.ranking.gameVersion='0.34.0-prebeta';}s.floor=8;s.room=s.floors[8].findIndex(r=>r.type==='boss');challengeCommander(s);const r=currentRoom(s),e=r.enemies[0];if(phase===2){e.hp=e.max*.4;e.commander.phase=2;}const c=e.commander;Object.assign(c,{rainClock:20,blinkClock:20,snipeClock:20,volleyClock:20,ricochetClock:20});return {s,r,e,c,p:s.player};}
test('new commanders increase volley density and speed while legacy saves keep old attacks',()=>{for(const phase of [1,2])for(const legacy of [false,true]){const {s,r,e,c,p}=commander(phase,legacy),b=[];c.volleyClock=0;updateCommander(e,p,r,.01,b,()=>{});const count=legacy?(phase===1?2:3):(phase===1?4:6);assert.equal(c.volley.count,count);const restored=parseSave(encodeSave(s));assert.equal(currentRoom(restored).enemies[0].bossPressureVersion,legacy?undefined:1);updateCommander(e,p,r,c.volley.time,b,()=>{});assert.equal(b.length,count);assert.ok(Math.abs(Math.hypot(b[0].vx,b[0].vy)-(legacy?290:phase===1?360:400)*attackProfile(e).speed)<1e-7);updateCommander(e,p,r,c.volley.time,b,()=>{});assert.equal(b.length,count*2);}});
test('reflection warns before firing two or four rounds, survives save and bounces once',()=>{for(const phase of [1,2]){const {s,r,e,c,p}=commander(phase),b=[];c.ricochetClock=0;updateCommander(e,p,r,.01,b,()=>{});assert.equal(b.length,0);assert.equal(c.ricochet.count,phase===1?2:4);const loaded=parseSave(encodeSave(s)),other=[];updateCommander(currentRoom(loaded).enemies[0],loaded.player,currentRoom(loaded),c.ricochet.time,other,()=>{});updateCommander(e,p,r,c.ricochet.time,b,()=>{});assert.deepEqual(b,other);assert.ok(b.every(v=>v.ricochet&&v.bounces===1));const round={...b[0],x:929,y:200,vx:400,vy:0};advanceRicochet(round,.02,[],{x:480,y:400});assert.equal(round.bounces,0);assert.ok(round.vx<0);advanceRicochet(round,3,[],{x:480,y:400});assert.equal(round.life,0);resetCommanderAttack(e);assert.equal(c.ricochet,undefined);}});
test('phase two blinks into a telegraphed volley and casts rain on an eight second clock',()=>{const {s,r,e,c,p}=commander(2),b=[];c.blinkClock=0;updateCommander(e,p,r,.01,b,()=>{});assert.ok(c.blink);updateCommander(e,p,r,.4,b,()=>{});assert.equal(c.blinkClock,3.5);assert.equal(c.volley.count,6);assert.equal(b.length,0);delete c.volley;c.rainClock=0;updateCommander(e,p,r,.01,b,()=>{});assert.equal(c.rainClock,8);assert.equal(c.rain.time,.75);assert.doesNotThrow(()=>parseSave(encodeSave(s)));});
test('new commander travels farther and continues movement during early volley preparation',()=>{let distances=[];for(const legacy of [true,false]){const {e,c,p,r}=commander(1,legacy),b=[];const origin={x:e.x,y:e.y};for(let i=0;i<30;i++)updateCommander(e,p,r,1/60,b,()=>{});distances.push(Math.hypot(e.x-origin.x,e.y-origin.y));}assert.ok(distances[1]>distances[0]*1.6);const {e,c,p,r}=commander();c.volley={aim:0,count:4,time:.42,fired:0};const x=e.x;updateCommander(e,p,r,.1,[],()=>{});assert.notEqual(e.x,x);});
test('only new king phase three accelerates judgment and its dash without losing telegraphs',()=>{for(const legacy of [false,true])for(const ratio of [1,.5,.25]){const s=newRun(42);if(legacy){s.generationVersion=30;s.ranking.gameVersion='0.34.0-prebeta';}s.floor=7;s.room=s.floors[7].findIndex(r=>r.type==='boss');const r=currentRoom(s);r.enemies=[];challengeKing(s);const e=r.enemies[0];e.hp=e.max*ratio;const fast=!legacy&&ratio===.25;startUpperAttack(e,'judgment',s.player,r);assert.equal(e.darkAttack.time,fast?.8:1.1);assert.doesNotThrow(()=>parseSave(encodeSave(s)));updateUpper(e,s.player,r,e.darkAttack.time,[],()=>{});assert.equal(e.darkAttack.step,1);assert.equal(e.darkAttack.time,fast?.42:.65);startUpperAttack(e,'dash',s.player,r);const warning=e.darkAttack.time;updateUpper(e,s.player,r,warning,[],()=>{});assert.equal(e.darkAttack.moving,true);updateUpper(e,s.player,r,fast?.24:.32,[],()=>{});assert.equal(e.darkAttack,undefined);}});
