import test from 'node:test';
import assert from 'node:assert/strict';
import {newRun,currentRoom} from '../../src/game/engine.js';
import {challengeDemon,advanceDemonPhase,tryDemonHole,updateDemon,routeOpen} from '../../src/combat/demon.js';
import {updateDemonSpecials,tryDemonBolt} from '../../src/combat/demon-specials.js';
import {stepRun,enterRoom} from '../../src/game/simulation.js';
import {hitEnemy} from '../../src/progression/progression.js';
import {enemyDamageFactor} from '../../src/combat/enemy-defense.js';
import {castBlink,castUltimate,usePotion} from '../../src/combat/abilities.js';
import {castUtility} from '../../src/combat/utility.js';
import {blocked,segmentBlocked} from '../../src/world/terrain.js';
import {encodeSave,parseSave} from '../../src/persistence/storage.js';
function fight(phase=1,legacy=false){const s=newRun(77,{campaign:'expanded'});if(legacy)s.generationVersion=31;s.floor=9;s.room=1;s.player.x=800;s.player.y=410;challengeDemon(s);const r=currentRoom(s);while(r.demon.phase<phase){r.enemies.forEach(e=>e.hp=0);advanceDemonPhase(r,s.projectiles);}const d=r.demon;d.recovery=0;return {s,r,d,p:s.player};}
function attack(e,kind,p,extra={}){return {kind,owner:e.part,time:.01,x:e.x,y:e.y,tx:p.x,ty:p.y,aim:0,...extra};}
test('new demon uses separate clocks and wider hand salvos; old runs stay serial',()=>{const {s,r,d,p}=fight();d.partClocks={hand:0,foot:0};updateDemon(s,r,p,.01,[],()=>{});assert.equal(d.attacks.length,2);assert.equal(d.attack,null);assert.ok(d.attacks.find(a=>a.owner==='foot').time<=.75);const counts=[];for(let i=0;i<5;i++){const b=[];d.attacks=[attack(r.enemies[0],'hand',p,{finger:i})];d.partClocks={hand:3,foot:3};updateDemon(s,r,p,.02,b,()=>{});counts.push(b.length);}assert.deepEqual(counts,[9,5,5,5,11]);assert.equal(fight(1,true).d.pressureVersion,undefined);assert.doesNotThrow(()=>parseSave(encodeSave(s)));});
test('foot shield blocks a complete elemental hit once and recharges without stacking',()=>{const {s,r,d,p}=fight(),foot=r.enemies[1];const hp=foot.hp;s.entryGrace=0;s.attack=99;stepRun(s,.02);assert.equal(foot.demonShield,true,'zero damage must not consume shield');hitEnemy({...p,frost:4},foot,r.enemies,[],1,true,r);assert.equal(foot.hp,hp);assert.equal(foot.frostStacks||0,0);assert.equal(foot.demonShield,false);hitEnemy(p,foot,r.enemies,[],1,false,r);assert.ok(foot.hp<hp);d.partClocks={hand:3,foot:3};foot.demonShieldClock=.01;updateDemon(s,r,p,.02,[],()=>{});assert.equal(foot.demonShield,true);assert.equal(foot.demonShieldClock,5);assert.equal(enemyDamageFactor(foot),0);assert.equal(enemyDamageFactor(foot),1);assert.doesNotThrow(()=>parseSave(encodeSave(s)));});
test('large footprints exceed four while blocking shots and preserving the exit route',()=>{const {s,r,p}=fight();let count=0;for(const y of [200,340])for(const x of [230,360,600,730])if(tryDemonHole(r,x,y,p))count++;assert.ok(count>4,'placed '+count);assert.ok(r.obstacles.every(o=>o.w===80&&o.h===70));assert.ok(r.enemies.every(e=>!blocked(e.x,e.y,32,r.obstacles)));assert.equal(tryDemonHole(r,r.enemies[0].x,r.enemies[0].y,p),false);const h=r.obstacles[0],c={x:h.x+40,y:h.y+35};assert.ok(blocked(c.x,c.y,10,r.obstacles));assert.ok(segmentBlocked({x:c.x-50,y:c.y},{x:c.x+50,y:c.y},r.obstacles));assert.ok(routeOpen(r.obstacles,p,[{x:60,y:270}]));assert.doesNotThrow(()=>parseSave(encodeSave(s)));assert.equal(tryDemonHole(r,60,270,p),false);});
test('eye adds seven curved projectiles and nose trail remains continuous during strong mouth pull',()=>{const {s,r,d,p}=fight(2),eye=r.enemies.find(e=>e.part==='eye'),nose=r.enemies.find(e=>e.part==='nose'),mouth=r.enemies.find(e=>e.part==='mouth');d.partClocks={eye:3,nose:3,mouth:3};d.attacks=[attack(eye,'eyeOrb',p)];const b=[];updateDemon(s,r,p,.02,b,()=>{});assert.equal(b.length,7);assert.ok(b.some(b=>b.demonCurve>0)&&b.some(b=>b.demonCurve<0));d.attacks=[attack(nose,'noseTrail',p,{tx:400,ty:270})];updateDemon(s,r,p,.02,[],()=>{});assert.ok(d.trails.length>=6);for(let i=1;i<d.trails.length;i++)assert.ok(Math.hypot(d.trails[i].x-d.trails[i-1].x,d.trails[i].y-d.trails[i-1].y)<=68);p.x=mouth.x+300;p.y=mouth.y;d.attacks=[attack(mouth,'mouthPull',p)];updateDemon(s,r,p,.02,[],()=>{});assert.ok(d.trails.length>0);assert.equal(d.force.time,1.2);const x=p.x;updateDemon(s,r,p,.2,[],()=>{});assert.ok(x-p.x>=44);assert.doesNotThrow(()=>parseSave(encodeSave(s)));});
test('three-second specials lock their target, resume deterministically, deal two then one hearts',()=>{for(const kind of ['flame','ice','zeus']){const {s,r,d,p}=fight(3);d.summonClock=6;d.special={kind,x:400,y:300,radius:60,time:3};const loaded=parseSave(encodeSave(s));p.x=700;const b=[];updateDemonSpecials(s,r,p,2,b,()=>{},routeOpen);assert.equal(d.special.x,400);assert.equal(d.special.time,1);assert.equal(b.length,0);loaded.player.x=700;updateDemonSpecials(loaded,currentRoom(loaded),loaded.player,2,[],()=>{},routeOpen);assert.deepEqual(currentRoom(loaded).demon.special,d.special);p.x=400;p.y=300;let raw=[];updateDemonSpecials(s,r,p,1,b,n=>raw.push(n),routeOpen);assert.deepEqual(raw,[18]);assert.equal(d.special.time,3);if(kind==='ice'){assert.equal(b.length,12);assert.ok(b.every(b=>b.damage===9&&b.demonIce));}if(kind==='flame'){assert.equal(d.fields[0].time,3);updateDemonSpecials(s,r,p,.1,b,n=>raw.push(n),routeOpen);assert.equal(raw.at(-1),9);}assert.doesNotThrow(()=>parseSave(encodeSave(s)));}
 const {s,r,d,p}=fight(3);p.max=p.hp=10;s.entryGrace=0;s.attack=99;d.partClocks={core:3};d.special={kind:'flame',x:p.x,y:p.y,radius:60,time:.01};stepRun(s,.02);assert.equal(p.hp,8);stepRun(s,.1);assert.equal(p.hp,8,'invulnerability prevents same impact plus field damage');});
test('electric aura stuns every player action without damage and has a shared retrigger grace',()=>{const {s,r,d,p}=fight(3);assert.ok(tryDemonBolt(r,400,300,p,routeOpen));p.x=440;p.y=300;s.entryGrace=0;s.invulnerable=0;d.partClocks={core:3};d.specialClock=3;d.summonClock=6;const hp=p.hp;updateDemonSpecials(s,r,p,.01,[],()=>{},routeOpen);assert.equal(p.actionStun,1);assert.equal(p.hp,hp);p.hp=3;p.potions=2;p.utility='guardian';p.level=4;p.ultimate=1;p.evolutions={ultimate:'burst'};assert.equal(usePotion(s),false);assert.equal(castBlink(s,{x:1,y:0}),false);assert.equal(castUltimate(s),false);assert.equal(castUtility(s),false);const x=p.x;s.attack=0;const result=stepRun(s,.1,{x:1,y:0});assert.equal(p.x,x);assert.ok(!result.events.includes('shot'));assert.ok(p.actionStun<1);assert.doesNotThrow(()=>parseSave(encodeSave(s)));p.actionStun=0;updateDemonSpecials(s,r,p,.01,[],()=>{},routeOpen);assert.equal(p.actionStun,0);p.electricGrace=0;s.invulnerable=.5;updateDemonSpecials(s,r,p,.01,[],()=>{},routeOpen);assert.equal(p.actionStun,0);});
test('summons are two per interval, capped at eight and award no kills, XP or rankings',()=>{const {s,r,d,p}=fight(3);d.specialClock=3;for(let i=0;i<6;i++){d.summonClock=0;updateDemonSpecials(s,r,p,.01,[],()=>{},routeOpen);}const summons=r.enemies.filter(e=>e.summoned);assert.equal(summons.length,8);assert.ok(summons.every(e=>e.spawnGrace===1&&Math.hypot(e.x-p.x,e.y-p.y)>170));assert.equal(new Set(r.enemies.map(e=>e.id)).size,r.enemies.length);assert.doesNotThrow(()=>parseSave(encodeSave(s)));const xp=p.xp,kills=s.kills,rank=s.ranking.defeated.length;summons.forEach(e=>e.hp=0);s.entryGrace=0;s.invulnerable=99;stepRun(s,.02);assert.equal(p.xp,xp);assert.equal(s.kills,kills);assert.equal(s.ranking.defeated.length,rank);});
test('phase changes retain pits; reentry cancels pending specials; death clears bolts and summons',()=>{const {s,r,d,p}=fight(3);assert.ok(tryDemonHole(r,360,300,p));assert.ok(tryDemonBolt(r,600,300,p,routeOpen));d.special={kind:'zeus',x:400,y:300,radius:60,time:2};enterRoom(s);assert.equal(d.special,null);assert.ok(r.obstacles.some(o=>o.demonHole)&&r.obstacles.some(o=>o.demonBolt));r.enemies[0].hp=0;s.entryGrace=0;stepRun(s,.02);assert.equal(s.key,true);assert.ok(!r.obstacles.some(o=>o.demonBolt));assert.ok(r.obstacles.some(o=>o.demonHole));assert.equal(d.fields.length,0);assert.doesNotThrow(()=>parseSave(encodeSave(s)));});
test('two minutes of every phase stay bounded and round-trip at each checkpoint',()=>{for(const phase of [1,2,3]){const {s,r,p}=fight(phase);s.entryGrace=0;s.invulnerable=999;s.attack=999;p.max=p.hp=100;let total=0;for(let i=0;i<2400;i++){p.x=480+Math.sin(i/80)*230;p.y=300+Math.cos(i/130)*100;stepRun(s,.05);total+=s.projectiles.length;if(i%100===0)assert.doesNotThrow(()=>parseSave(encodeSave(s)));}assert.ok(total>0);assert.ok(r.enemies.length<=9);assert.ok(s.projectiles.length<2000);assert.ok(routeOpen(r.obstacles,p,[{x:60,y:270}]));}});

test('specials telegraph the room edge rather than leaving a safe border band',()=>{const {s,r,d,p}=fight(3);p.x=910;p.y=475;d.special=null;d.specialClock=0;d.summonClock=6;updateDemonSpecials(s,r,p,0,[],()=>{},routeOpen);assert.equal(d.special.x,p.x);assert.equal(d.special.y,p.y);assert.doesNotThrow(()=>parseSave(encodeSave(s)));});
