import test from 'node:test';import assert from 'node:assert/strict';
import {newRun} from '../../src/game/engine.js';import {RunStore,encodeSave,parseSave,validateRun} from '../../src/persistence/storage.js';
const memory=()=>{const m=new Map();return {getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k)};};
test('versioned save round trips projectiles, phases, food, and metrics',()=>{const s=newRun(21);s.projectiles=[{x:100,y:100,vx:330,vy:0,life:4,enemy:true,ricochet:true,bounces:0,hit:[]}];s.pendingHeal=true;s.shield=12;const loaded=parseSave(encodeSave(s));assert.deepEqual(loaded,JSON.parse(JSON.stringify(s)));});
test('rejects broken values, impossible current room, unsupported version and corrupt checksum',()=>{const s=newRun(21);for(const mutate of [s=>s.player.hp=Infinity,s=>s.room=999,s=>s.version=999,s=>s.floors[0][0].enemies=[{type:'script'}]]){const copy=structuredClone(s);mutate(copy);assert.throws(()=>validateRun(copy));}const text=encodeSave(s).replace('"checksum":"','"checksum":"wrong');assert.throws(()=>parseSave(text));});
test('backup recovers last good save and terminal tombstone prevents dead-run resurrection',()=>{const data=memory(),store=new RunStore(data),s=newRun(1);assert.ok(store.write(s).ok);s.elapsed=2;assert.ok(store.write(s).ok);data.setItem(store.key,'broken');assert.equal(store.read().recovered,true);assert.equal(store.read().run.elapsed,0);s.status='dead';assert.ok(store.complete(s,false).ok);assert.equal(store.read().run,undefined);data.setItem(store.key+'.backup',encodeSave({...s,status:'playing'}));assert.equal(store.read().run,undefined);});
test('storage exceptions become explicit failure, not a false save confirmation',()=>{const store=new RunStore({getItem(){throw Error('denied');},setItem(){throw Error('quota');}});assert.ok(store.read().error);assert.equal(store.write(newRun()).ok,false);});
test('quota on the optional backup still saves the current run without losing the old main',()=>{
 const s=newRun(1),limit=encodeSave(s).length+200,values=new Map(),storage={getItem:k=>values.get(k)??null,removeItem:k=>values.delete(k),setItem(k,v){const total=[...values].filter(([name])=>name!==k).reduce((n,[name,value])=>n+name.length+value.length,0)+k.length+v.length;if(total>limit)throw Object.assign(Error('full'),{name:'QuotaExceededError'});values.set(k,v);}};
 const store=new RunStore(storage);assert.equal(store.write(s).ok,true);s.elapsed=1;assert.equal(store.write(s).ok,true);assert.equal(store.read().run.elapsed,1);assert.equal(storage.getItem(store.key+'.backup'),null);
 s.projectiles=Array.from({length:200},(_,i)=>({x:i,y:100,vx:0,vy:0,life:2,enemy:false,hit:[]}));const failed=store.write(s);assert.equal(failed.reason,'quota');assert.equal(store.read().run.elapsed,1);
});
test('invalid game state is reported separately from browser storage errors',()=>{
 const s=newRun(1),store=new RunStore(memory());s.player.hp=Infinity;const result=store.write(s);assert.equal(result.reason,'invalid_state');assert.equal(store.read().run,undefined);
});
test('legacy raw saves are accepted and strengthened only once',()=>{const s=newRun();delete s.healthVersion;s.player.hp=80;s.player.max=100;const first=parseSave(JSON.stringify(s));assert.equal(first.player.hp,4);assert.equal(first.player.max,5);assert.deepEqual(parseSave(encodeSave(first)),first);});
